import {SNAPSHOT_INTERACTION_JS} from './visual-interactions.js';
import { getState, setState } from './db.js';
import { assertPublicUrl } from './network.js';
import { sourceText } from './scraper.js';

const TICKET_TTL_MS=10*60*1000;
type VisualContext='list'|'detail';
type Ticket={url:string;createdAt:number;indirect?:boolean};
const ticketKey=(id:string)=>`visual_ticket:${id}`;
export async function createVisualTicket(url:string,indirect=false):Promise<string>{assertPublicUrl(url);const id=crypto.randomUUID();await setState(ticketKey(id),{url,createdAt:Date.now(),indirect});return id}
async function consumeTicket(id:string):Promise<Ticket>{const ticket=await getState<Ticket|null>(ticketKey(id),null);if(!ticket||Date.now()-ticket.createdAt>TICKET_TTL_MS)throw new Error('لینک انتخاب بصری منقضی یا نامعتبر است.');await setState(ticketKey(id),null);return ticket}

const LIST_OPTIONS=`<option value="container">📦 کانتینر محصول</option><option value="title">📝 عنوان</option><option value="price">💰 قیمت</option><option value="link">🔗 لینک</option><option value="image">🖼 تصویر فهرست</option>`;
const DETAIL_OPTIONS=`<option value="shortDesc">توضیحات کوتاه</option><option value="longDesc">توضیحات بلند</option><option value="sku">SKU</option><option value="category">دسته‌بندی</option><option value="tags">برچسب‌ها</option><option value="weight">وزن</option><option value="stock">موجودی</option><option value="brand">برند</option><option value="detailImage">عکس اصلی محصول</option><option value="variations">تنوع‌ها</option><option value="galleryBox">باکس گالری</option><option value="galleryOne">عکس‌های گالری</option>`;
function toolbar(context:VisualContext){const detail=context==='detail';return `<div id="__s4bar" data-context="${context}"><div class="__s4row"><select id="__s4mode" aria-label="فیلد در حال انتخاب">${detail?DETAIL_OPTIONS:LIST_OPTIONS}</select><button id="__s4up" title="والد">⬆ والد</button><button id="__s4down" title="فرزند">⬇ فرزند</button><button id="__s4prev" title="هم‌سطح قبلی">→ قبلی</button><button id="__s4next" title="هم‌سطح بعدی">← بعدی</button><code id="__s4selector">روی عنصر مورد نظر کلیک کنید</code><span id="__s4count">۰ مورد</span><button id="__s4pause" title="موقتاً انتخاب را خاموش کن تا بتوانی تب‌ها و کشویی‌های صفحه را باز کنی">⏸ توقف انتخاب</button><button id="__s4refresh" title="دریافت دوبارهٔ صفحه؛ انتخاب‌های ثبت‌شده حفظ می‌شوند">↻ ریفرش</button><button id="__s4dismiss" disabled title="در حالت توقف، پاپ‌آپ را فقط از این تصویر پنهان کن">پنهان‌کردن پاپ‌آپ</button><span id="__s4interaction" role="status">تصویر ثابت؛ ثبت و رفتن به فیلد بعدی</span><button id="__s4save">✓ ثبت و بعدی</button>${detail?'<button id="__s4done">✅ اتمام و اعمال همه</button>':''}</div><div class="__s4meta"><b id="__s4field">${detail?'توضیحات کوتاه':'کانتینر محصول'}</b><span id="__s4preview">هنوز عنصری انتخاب نشده است.</span><span id="__s4progress">۰ فیلد ثبت‌شده</span></div></div>`}
const STYLE=`<style>
#__s4bar{position:fixed;z-index:2147483647;top:0;left:0;right:0;background:#111827;color:#fff;padding:8px;font:12px Tahoma,sans-serif;box-shadow:0 3px 14px #0008;direction:rtl}#__s4bar .__s4row{display:flex;gap:6px;align-items:center;flex-wrap:wrap}#__s4bar .__s4meta{display:flex;gap:8px;align-items:center;margin-top:6px;padding-top:6px;border-top:1px solid #334155}#__s4bar select,#__s4bar button{font:inherit;border:1px solid #475569;border-radius:7px;padding:7px;background:#1f2937;color:white}#__s4bar button{cursor:pointer}#__s4bar button:disabled{opacity:.45;cursor:default}#__s4bar button:hover{background:#334155}#__s4bar #__s4save{background:#166534;border-color:#22c55e}#__s4bar #__s4done{background:#075985;border-color:#38bdf8}#__s4selector{direction:ltr;background:#020617;color:#67e8f9;padding:7px;border-radius:6px;min-width:160px;max-width:34vw;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex:1}#__s4count{background:#422006;color:#fde68a;border-radius:999px;padding:5px 9px;white-space:nowrap}#__s4field{color:#bfdbfe}#__s4preview{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex:1;color:#bbf7d0}#__s4progress{color:#cbd5e1;white-space:nowrap}.__s4hover{outline:3px solid #38bdf8!important;outline-offset:2px!important}.__s4picked{outline:3px solid #22c55e!important;outline-offset:3px!important;background-color:#22c55e18!important}
@media(max-width:720px){#__s4bar{padding:6px;font-size:11px}#__s4bar .__s4row{gap:4px}#__s4bar button,#__s4bar select{padding:6px 7px}#__s4selector{order:8;min-width:55%;max-width:none}#__s4bar .__s4meta{align-items:flex-start;flex-wrap:wrap}#__s4preview{flex-basis:70%}}
body{padding-top:104px!important}
#__s4bar button.__s4on{background:#f59e0b;color:#111827;font-weight:bold}
body.__s4paused #__s4bar{opacity:.92}
body.__s4paused{cursor:auto}</style>`;
const PICKER_JS=String.raw`<script>(function(){
${SNAPSHOT_INTERACTION_JS}
const context='__S4_CONTEXT__',bar=document.getElementById('__s4bar'),modeSelect=document.getElementById('__s4mode'),selectorText=document.getElementById('__s4selector'),countText=document.getElementById('__s4count'),previewText=document.getElementById('__s4preview'),fieldText=document.getElementById('__s4field'),progressText=document.getElementById('__s4progress'),selections={};let selected=null,hovered=null;
const labels={container:'کانتینر محصول',title:'عنوان',price:'قیمت',link:'لینک',image:'تصویر فهرست',shortDesc:'توضیحات کوتاه',longDesc:'توضیحات بلند',sku:'SKU',category:'دسته‌بندی',tags:'برچسب‌ها',weight:'وزن',stock:'موجودی',brand:'برند',detailImage:'عکس اصلی محصول',variations:'تنوع‌ها',galleryBox:'باکس گالری',galleryOne:'عکس‌های گالری'};
const fields=Array.from(modeSelect.options).map(option=>option.value),cssEscape=value=>window.CSS&&CSS.escape?CSS.escape(value):String(value).replace(/[^a-zA-Z0-9_-]/g,char=>'\\'+char.charCodeAt(0).toString(16)+' ');
function validId(value){return value&&value.length<64&&!/^(__|\d)/.test(value)&&!/^[a-f\d]{16,}$/i.test(value)}
function stableClass(value){return value&&value.length>1&&value.length<48&&!/^(__|active$|open$|show$|hide$|hidden$|selected$|current$|is-|js-|has-)/i.test(value)&&!/[a-f\d]{18,}/i.test(value)}
function matches(value){if(!value)return 0;try{return document.querySelectorAll(value).length}catch{return 0}}
function classCandidates(el){const tag=el.tagName.toLowerCase(),classes=Array.from(el.classList).filter(stableClass).slice(0,5),out=[];for(let size=Math.min(3,classes.length);size>=1;size--)out.push(tag+classes.slice(0,size).map(value=>'.'+cssEscape(value)).join(''));for(const value of classes)out.push(tag+'.'+cssEscape(value));return Array.from(new Set(out))}
function selector(el){
  if(!el||['BODY','HTML'].includes(el.tagName))return'';const tag=el.tagName.toLowerCase(),candidates=classCandidates(el),repeatMode=context==='list'||modeSelect.value==='container';
  if(repeatMode){const repeated=candidates.find(value=>matches(value)>1);if(repeated)return repeated}
  if(context==='detail'&&validId(el.id))return tag+'#'+cssEscape(el.id);
  if(candidates.length)return candidates[0];
  for(const attr of ['itemprop','data-testid','data-test','role']){const value=el.getAttribute(attr);if(value&&value.length<80){const candidate=tag+'['+attr+'="'+String(value).replace(/["\\]/g,'\\$&')+'"]';if(!repeatMode||matches(candidate)>1)return candidate}}
  if(validId(el.id))return tag+'#'+cssEscape(el.id);
  let parent=el.parentElement,depth=0;while(parent&&depth++<4){const parentCandidates=classCandidates(parent),parentBase=parentCandidates.find(value=>!repeatMode||matches(value+' '+tag)>1)||parentCandidates[0];if(parentBase)return parentBase+' '+tag;if(validId(parent.id))return parent.tagName.toLowerCase()+'#'+cssEscape(parent.id)+' '+tag;parent=parent.parentElement}
  return tag
}
function targetFor(el,mode){if(mode==='link')return el.closest('a[href]')||el.querySelector('a[href]')||el;if(['image','detailImage','galleryOne'].includes(mode))return(el.tagName==='IMG'?el:el.querySelector('img'))||el;return el}
function preview(el,mode){if(!el)return'';if(mode==='link'){const link=el.closest('a[href]')||el.querySelector('a[href]');return link?.href||''}if(['image','detailImage','galleryOne'].includes(mode)){const image=el.tagName==='IMG'?el:el.querySelector('img');return image?.currentSrc||image?.src||el.getAttribute('data-src')||''}if(mode==='galleryBox')return (el.querySelectorAll('img,source,[data-src],[data-large_image]').length||0)+' تصویر داخل باکس';if(mode==='variations')return Array.from(el.querySelectorAll('option,[data-value]')).map(x=>(x.textContent||x.getAttribute('data-value')||'').trim()).filter(Boolean).slice(0,6).join('، ');return(el.textContent||'').replace(/\s+/g,' ').trim().slice(0,180)}
function updateProgress(){progressText.textContent=Object.keys(selections).filter(key=>selections[key]?.selector).length.toLocaleString('fa-IR')+' از '+fields.length.toLocaleString('fa-IR')+' فیلد ثبت‌شده'}
function paint(el){if(!el||el===bar||el.closest('#__s4bar'))return;const mode=modeSelect.value,target=targetFor(el,mode);if(selected)selected.classList.remove('__s4picked');selected=target;selected.classList.add('__s4picked');const value=selector(target),count=matches(value),sample=preview(target,mode);selections[mode]={selector:value,count,preview:sample};selectorText.textContent=value;countText.textContent=count.toLocaleString('fa-IR')+' مورد';previewText.textContent=sample||'پیش‌نمایشی پیدا نشد.';fieldText.textContent=labels[mode]||mode;updateProgress()}
function restoreMode(){const mode=modeSelect.value,stored=selections[mode];fieldText.textContent=labels[mode]||mode;if(selected)selected.classList.remove('__s4picked');selected=null;if(stored?.selector){try{selected=document.querySelector(stored.selector);selected?.classList.add('__s4picked')}catch{}selectorText.textContent=stored.selector;countText.textContent=matches(stored.selector).toLocaleString('fa-IR')+' مورد';previewText.textContent=stored.preview||'ثبت شده است.'}else{selectorText.textContent='روی عنصر مربوط به «'+(labels[mode]||mode)+'» کلیک کنید';countText.textContent='۰ مورد';previewText.textContent='هنوز عنصری برای این فیلد انتخاب نشده است.'}updateProgress()}
function sendOne(){const mode=modeSelect.value,item=selections[mode];if(!item?.selector){previewText.textContent='ابتدا یک عنصر را انتخاب کنید.';return}parent.postMessage({type:'scraper4-selector',channel:'__S4_CHANNEL__',mode,...item},'*');const index=fields.indexOf(mode);if(index>=0&&index<fields.length-1){modeSelect.value=fields[index+1];restoreMode()}else{previewText.textContent='آخرین فیلد ثبت شد.';}}
function move(direction){if(!selected)return;let next=direction==='up'?selected.parentElement:direction==='down'?selected.firstElementChild:direction==='prev'?selected.previousElementSibling:selected.nextElementSibling;if(next&&!next.closest('#__s4bar'))paint(next)}
document.addEventListener('mouseover',event=>{if(!picking)return;const target=event.target;if(!(target instanceof Element)||target.closest('#__s4bar'))return;if(hovered&&hovered!==selected)hovered.classList.remove('__s4hover');hovered=target;if(target!==selected)target.classList.add('__s4hover')},true);
document.addEventListener('mouseout',event=>{if(!picking)return;const target=event.target;if(target instanceof Element&&target!==selected)target.classList.remove('__s4hover')},true);
let picking=true;
const pauseButton=document.getElementById('__s4pause');
function setPicking(value){picking=value;s4InteractionMode(picking);pauseButton.textContent=picking?'\u23f8 \u062a\u0648\u0642\u0641 \u0627\u0646\u062a\u062e\u0627\u0628':'\u25b6 \u0627\u062f\u0627\u0645\u0647 \u0627\u0646\u062a\u062e\u0627\u0628';pauseButton.classList.toggle('__s4on',!picking);document.body.classList.toggle('__s4paused',!picking);if(!picking)document.querySelectorAll('.__s4hover').forEach(node=>node.classList.remove('__s4hover'));}
pauseButton.onclick=()=>setPicking(!picking);
// Paused interactions are local to sanitized HTML; source scripts remain disabled.
document.addEventListener('click',event=>{const target=event.target;if(!(target instanceof Element)||target.closest('#__s4bar'))return;if(!picking){s4SnapshotClick(event);return;}event.preventDefault();event.stopPropagation();paint(target)},true);
modeSelect.addEventListener('change',restoreMode);document.getElementById('__s4up').onclick=()=>move('up');document.getElementById('__s4down').onclick=()=>move('down');document.getElementById('__s4prev').onclick=()=>move('prev');document.getElementById('__s4next').onclick=()=>move('next');document.getElementById('__s4save').onclick=sendOne;
const done=document.getElementById('__s4done');if(done)done.onclick=()=>parent.postMessage({type:'scraper4-detail-selectors',channel:'__S4_CHANNEL__',selections},'*');
document.addEventListener('keydown',event=>{if(!picking)return;if(event.target instanceof HTMLInputElement||event.target instanceof HTMLTextAreaElement||event.target instanceof HTMLSelectElement)return;if(event.key==='ArrowUp'){event.preventDefault();move('up')}else if(event.key==='ArrowDown'){event.preventDefault();move('down')}else if(event.key==='ArrowRight'){event.preventDefault();move('prev')}else if(event.key==='ArrowLeft'){event.preventDefault();move('next')}else if(event.key==='Enter'){event.preventDefault();done?done.click():sendOne()}},true);window.addEventListener('message',event=>{if(event.source!==parent||event.data?.channel!=='__S4_CHANNEL__')return;if(event.data.type==='scraper4-mode'&&fields.includes(event.data.mode)){modeSelect.value=event.data.mode;restoreMode()}});restoreMode();
})();</script>`;
function pickerScript(context:VisualContext,channel:string){return PICKER_JS.replace('__S4_CONTEXT__',context).replaceAll('__S4_CHANNEL__',channel.replace(/[^a-z0-9-]/gi,''))}
function escapeAttr(value:string):string{return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!))}
function absolutize(value:string,base:string):string{try{return new URL(value,base).href}catch{return value}}

export async function renderVisualSelector(ticketId:string,context:VisualContext='list'):Promise<Response>{
  const ticket=await consumeTicket(ticketId),page=await sourceText(ticket.url,Boolean(ticket.indirect),5_000_000),finalUrl=page.url,contentType=page.contentType||'';
  if(!contentType.includes('text/html'))throw new Error('صفحهٔ انتخاب‌شده HTML نیست.');
  let html=page.text,baseTag=`<base href="${escapeAttr(finalUrl)}">`;
  html=html.replace(/<script\b[^>]*>[\s\S]*?<\/script\s*>/gi,'').replace(/<script\b[^>]*\/?>/gi,'').replace(/<base\b[^>]*>/gi,'').replace(/<meta\b[^>]*http-equiv\s*=\s*["']?content-security-policy["']?[^>]*>/gi,'').replace(/<meta\b[^>]*http-equiv\s*=\s*["']?refresh["']?[^>]*>/gi,'').replace(/\s+on[a-z]+\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+)/gi,'').replace(/\s+(href|src|action)\s*=\s*(["'])\s*javascript:[\s\S]*?\2/gi,'');
  html=html.replace(/<(img|source)\b([^>]*?)\s(?:data-src|data-lazy-src|data-original)=(['"])(.*?)\3([^>]*)>/gi,(all,tag,before,_quote,url,after)=>new RegExp('\\ssrc\\s*=','i').test(`${before}${after}`)?all:`<${tag}${before} src="${escapeAttr(absolutize(url,finalUrl))}"${after}>`);
  const head=`${baseTag}${STYLE}`,body=`${toolbar(context)}${pickerScript(context,ticketId)}`;
  html=/<head\b[^>]*>/i.test(html)?html.replace(/<head\b[^>]*>/i,match=>match+head):`<head>${head}</head>${html}`;
  html=/<\/body\s*>/i.test(html)?html.replace(/<\/body\s*>/i,body+'</body>'):html+body;
  const trusted=pickerScript(context,ticketId).replace(/^<script>/,'').replace(/<\/script>$/,'');const hash=btoa(String.fromCharCode(...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(trusted)))));
  return new Response(html,{headers:{'content-type':'text/html; charset=UTF-8','cache-control':'no-store','content-security-policy':`sandbox allow-scripts; default-src 'none'; style-src 'unsafe-inline' https:; img-src data: blob: https:; font-src data: https:; script-src 'sha256-${hash}'; connect-src 'none'; frame-src 'none'; object-src 'none'; frame-ancestors 'self'; form-action 'none'; base-uri https:`,'x-content-type-options':'nosniff','referrer-policy':'no-referrer'}})
}
