import { build } from 'esbuild';

await build({
  entryPoints:['worker-src/main.ts'],
  outfile:'scraper4.worker.js',
  bundle:true,
  format:'esm',
  platform:'browser',
  target:'es2022',
  sourcemap:false,
  legalComments:'none',
  conditions:['worker','browser'],
  define:{'process.env.NODE_ENV':'"production"'},
  banner:{js:'/* Generated by npm run worker:build — edit worker-src/, not this bundle. */'},
  logLevel:'info'
});
