import express from 'express';
import cors from 'cors';
import path from 'node:path';
import fs from 'node:fs/promises';
import {execFile, spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {promisify} from 'node:util';
import {securityMiddleware, safePath, isDangerousCommand} from './security.js';
const execFileAsync=promisify(execFile); const __dirname=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(process.env.WORKSPACE_ROOT||path.join(__dirname,'..','workspace')); const modelsRoot=path.resolve(process.env.MODELS_ROOT||path.join(__dirname,'..','models')); const port=Number(process.env.PORT||3000),host=process.env.HOST||'127.0.0.1';
await fs.mkdir(root,{recursive:true}); await fs.mkdir(modelsRoot,{recursive:true}); const providersFile=path.resolve(process.env.PROVIDERS_FILE||path.join(modelsRoot,'providers.json'));

async function runCommand(command,timeout=120000){if(isDangerousCommand(command))return {code:403,stdout:'',stderr:'Blocked by safety policy'};return await new Promise(resolve=>{const c=spawn('/bin/sh',['-lc',command],{cwd:root,env:{...process.env,HOME:process.env.HOME||root},stdio:['ignore','pipe','pipe']});let stdout='',stderr='';const max=Number(process.env.MAX_OUTPUT_BYTES||200000);c.stdout.on('data',b=>stdout+=b);c.stderr.on('data',b=>stderr+=b);const t=setTimeout(()=>c.kill('SIGTERM'),timeout);c.on('close',code=>{clearTimeout(t);resolve({code,stdout:stdout.slice(-max),stderr:stderr.slice(-max)})})})}
async function verifyWorkspace(){const results=[];let entries=[];try{entries=await fs.readdir(root,{withFileTypes:true})}catch{};const files=entries.filter(e=>e.isFile()).map(e=>e.name);for(const f of files){if(f.endsWith('.js'))results.push({file:f,...await runCommand('node --check '+JSON.stringify(f),30000)});if(f.endsWith('.py'))results.push({file:f,...await runCommand('python3 -m py_compile '+JSON.stringify(f),30000)});if(f.endsWith('.php'))results.push({file:f,...await runCommand('php -l '+JSON.stringify(f),30000)})}try{const pkg=JSON.parse(await fs.readFile(path.join(root,'package.json'),'utf8'));if(pkg.scripts?.test)results.push({file:'package.json',...await runCommand('npm test -- --runInBand',120000)})}catch{}return results}
function providerNormalize(input){if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Provider JSON must be an object');const out={};for(const [id,v] of Object.entries(input)){if(!v||typeof v!=='object')continue;out[String(id)]={id:String(v.id||id),name:String(v.name||id),vendor:String(v.vendor||''),url:String(v.url||''),apiKey:String(v.apiKey||''),enabled:Boolean(v.enabled)}}return out}
const app=express(); app.use(cors()); app.use(express.json({limit:'2mb'})); app.use(securityMiddleware); app.use(express.static(path.join(__dirname,'..','public'))); const send=(r,d)=>r.json(d);
app.get('/api/health',async(_,r)=>send(r,{ok:true,node:process.version}));
app.get('/api/runtime',async(_,r)=>{const cmds=[['node','--version'],[process.env.PYTHON_BIN||'python3','--version'],['php','-v'],[process.env.LLAMA_BIN||'llama-server','--version']];const o={};for(const[c,a]of cmds){try{const x=await execFileAsync(c,[a],{timeout:5000});o[c]=(x.stdout||x.stderr).trim().split('\\n')[0]}catch{o[c]=null}}send(r,o)});
app.get('/api/files',async(q,r)=>{const d=safePath(root,String(q.query.path||''));const e=await fs.readdir(d,{withFileTypes:true});send(r,e.map(x=>({name:x.name,type:x.isDirectory()?'dir':'file'})).sort((a,b)=>a.type.localeCompare(b.type)||a.name.localeCompare(b.name)))});
app.get('/api/file',async(q,r)=>{const p=safePath(root,String(q.query.path||''));send(r,{path:path.relative(root,p),content:await fs.readFile(p,'utf8')})});
app.put('/api/file',async(q,r)=>{const p=safePath(root,String(q.body.path||''));await fs.mkdir(path.dirname(p),{recursive:true});await fs.writeFile(p,String(q.body.content??''));send(r,{ok:true})});
app.post('/api/mkdir',async(q,r)=>{await fs.mkdir(safePath(root,String(q.body.path||'')),{recursive:true});send(r,{ok:true})});
app.delete('/api/file',async(q,r)=>{await fs.rm(safePath(root,String(q.body.path||'')),{recursive:true});send(r,{ok:true})});
app.post('/api/terminal',async(q,r)=>{const command=String(q.body.command||'').trim();if(!command)return r.status(400).json({error:'command required'});if(isDangerousCommand(command))return r.status(403).json({error:'Blocked by safety policy'});const child=spawn('/bin/sh',['-lc',command],{cwd:root,env:{...process.env,HOME:process.env.HOME||root},stdio:['ignore','pipe','pipe']});let out='',err='';const max=Number(process.env.MAX_OUTPUT_BYTES||200000);child.stdout.on('data',b=>out+=b);child.stderr.on('data',b=>err+=b);const t=setTimeout(()=>child.kill('SIGTERM'),Number(q.body.timeout||process.env.COMMAND_TIMEOUT_MS||120000));child.on('close',code=>{clearTimeout(t);send(r,{code,stdout:out.slice(-max),stderr:err.slice(-max)})})});
app.get('/api/providers',async(_,r)=>{try{send(r,JSON.parse(await fs.readFile(providersFile,'utf8')))}catch{send(r,{})}});app.put('/api/providers',async(q,r)=>{const p=providerNormalize(q.body);await fs.mkdir(path.dirname(providersFile),{recursive:true});await fs.writeFile(providersFile,JSON.stringify(p,null,2));send(r,{ok:true,providers:p})});
app.get('/api/models',async(_,r)=>{const e=await fs.readdir(modelsRoot,{withFileTypes:true});send(r,e.filter(x=>x.isFile()&&/\\.gguf$/i.test(x.name)).map(x=>({name:x.name})))});
app.post('/api/models/download',async(q,r)=>{const url=String(q.body.url||'');const name=path.basename(new URL(url).pathname);if(!/\\.gguf$/i.test(name))return r.status(400).json({error:'Only GGUF downloads are supported'});const dest=safePath(modelsRoot,name);const x=await fetch(url);if(!x.ok)return r.status(x.status).json({error:'download failed'});const fh=await fs.open(dest,'w');try{const rd=x.body.getReader();while(true){const z=await rd.read();if(z.done)break;await fh.write(z.value)}}finally{await fh.close()}send(r,{ok:true,name})});
app.post('/api/models/launch',async(q,r)=>{const name=String(q.body.name||'');const model=safePath(modelsRoot,name);if(!name.endsWith('.gguf'))return r.status(400).json({error:'GGUF required'});const port=Number(q.body.port||8080);const c=spawn(process.env.LLAMA_BIN||'llama-server',['-m',model,'--host','127.0.0.1','--port',String(port),'-c',String(q.body.context||8192)],{cwd:root,detached:true,stdio:'ignore'});c.unref();send(r,{ok:true,pid:c.pid,baseUrl:'http://127.0.0.1:'+port+'/v1'})});
app.post('/api/agent',async(q,r)=>{const prompt=String(q.body.prompt||'').trim();const url=String(q.body.modelUrl||'http://127.0.0.1:8080/v1/chat/completions');const x=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({model:q.body.model||'local',messages:[{role:'system',content:'You are a professional autonomous coding agent. Work iteratively until verification passes. Return ONLY valid JSON: {"message":"...","actions":[{"type":"write","path":"relative/path","content":"complete file content"},{"type":"command","command":"safe command"}],"done":true}. You may inspect via command actions. After every execution result, use the feedback to fix errors. Never claim success without verification. Paths must stay inside the workspace.'},{role:'user',content:prompt}],temperature:.1,max_tokens:Number(q.body.maxTokens||4096)})});const d=await x.json();if(!x.ok)return r.status(x.status).json(d);send(r,{ok:true,text:d.choices?.[0]?.message?.content||JSON.stringify(d)})});
app.post('/api/agent/loop',async(q,r)=>{const prompt=String(q.body.prompt||'').trim();if(!prompt)return r.status(400).json({error:'prompt required'});const maxIterations=Math.min(20,Math.max(1,Number(q.body.maxIterations||8)));const modelUrl=String(q.body.modelUrl||'http://127.0.0.1:8080/v1/chat/completions');const messages=[{role:'system',content:'You are an autonomous senior coding agent. Execute a feedback loop. Return ONLY valid JSON: {"message":"...","actions":[{"type":"write","path":"relative/path","content":"complete file content"},{"type":"command","command":"safe command"}],"done":false}. Use commands to inspect and test. After tool results, fix every error you can. Stop only when verification is clean or you need user input. Never claim a change was made unless its write action was executed. Never use paths outside workspace.'},{role:'user',content:prompt}];const history=[];for(let i=1;i<=maxIterations;i++){const x=await fetch(modelUrl,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({model:q.body.model||'local',messages,temperature:.1,max_tokens:Number(q.body.maxTokens||6000)})});const d=await x.json();if(!x.ok)return r.status(x.status).json({error:d});const raw=d.choices?.[0]?.message?.content||'';let plan;try{plan=JSON.parse(raw.replace(/^\\`\\`\\`json\\s*|\\s*\\`\\`\\`$/g,''))}catch{messages.push({role:'user',content:'Your previous response was not valid JSON. Return only the required JSON object.'});history.push({iteration:i,error:'invalid JSON'});continue}const results=[];for(const a of (plan.actions||[])){if(a.type==='write'){try{const p=safePath(root,String(a.path));await fs.mkdir(path.dirname(p),{recursive:true});await fs.writeFile(p,String(a.content??''));results.push({type:'write',path:a.path,ok:true})}catch(e){results.push({type:'write',path:a.path,ok:false,error:e.message})}}else if(a.type==='command'){const z=await runCommand(String(a.command||''),Number(q.body.commandTimeout||120000));results.push({type:'command',command:a.command,code:z.code,stdout:z.stdout,stderr:z.stderr})}}const verification=await verifyWorkspace();const clean=verification.every(x=>x.code===0);history.push({iteration:i,message:plan.message,actions:results,verification,done:Boolean(plan.done&&clean)});if(plan.done&&clean)return send(r,{ok:true,success:true,iterations:i,history});messages.push({role:'assistant',content:JSON.stringify(plan)});messages.push({role:'user',content:JSON.stringify({executionResults:results,automaticVerification:verification,feedback:clean?'Verification is clean. If the requested work is complete, finish; otherwise continue.':'Verification has failures. Diagnose and fix them, then verify again.'})})}send(r,{ok:true,success:false,iterations:maxIterations,history,message:'Maximum iterations reached; review the latest verification results.'})});
app.use((req,res,next)=>{if(req.method==='GET'&&!req.path.startsWith('/api/'))return res.sendFile(path.join(__dirname,'..','public','index.html'));next()});app.use((e,_,r,__)=>(r.status(500).json({error:e.message})));app.listen(port,host,()=>console.log('Local Coding Agent on '+host+':'+port));