import express from 'express';
import cors from 'cors';
import path from 'node:path';
import fs from 'node:fs/promises';
import {execFile, spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {promisify} from 'node:util';
import {securityMiddleware, safePath, isDangerousCommand} from './security.js';

const execFileAsync=promisify(execFile);
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(process.env.WORKSPACE_ROOT||path.join(__dirname,'..','workspace'));
const modelsRoot=path.resolve(process.env.MODELS_ROOT||path.join(__dirname,'..','models'));
const port=Number(process.env.PORT||3000), host=process.env.HOST||'127.0.0.1';
await fs.mkdir(root,{recursive:true}); await fs.mkdir(modelsRoot,{recursive:true});
const app=express(); app.use(cors()); app.use(express.json({limit:'2mb'})); app.use(securityMiddleware); app.use(express.static(path.join(__dirname,'..','public')));
const send=(res,data)=>res.json(data);
app.get('/api/health',async(_,res)=>send(res,{ok:true,node:process.version,workspace:root}));
app.get('/api/runtime',async(_,res)=>{const cmds=[['node','--version'],[process.env.PYTHON_BIN||'python3','--version'],['php','-v'],[process.env.LLAMA_BIN||'llama-server','--version']]; const out={}; for(const [c,a] of cmds){try{const r=await execFileAsync(c,[a],{timeout:5000});out[c]=(r.stdout||r.stderr).trim().split('\\n')[0]}catch(e){out[c]=null}} send(res,out)});
app.get('/api/files',async(req,res)=>{const rel=String(req.query.path||''); const dir=safePath(root,rel); const ents=await fs.readdir(dir,{withFileTypes:true}); send(res,ents.map(e=>({name:e.name,type:e.isDirectory()?'dir':'file'})).sort((a,b)=>a.type.localeCompare(b.type)||a.name.localeCompare(b.name)))});
app.get('/api/file',async(req,res)=>{const p=safePath(root,String(req.query.path||'')); const st=await fs.stat(p); if(!st.isFile()) throw Error('Not a file'); send(res,{path:path.relative(root,p),content:await fs.readFile(p,'utf8')})});
app.put('/api/file',async(req,res)=>{const p=safePath(root,String(req.body.path||'')); if(!String(req.body.path||'')) return res.status(400).json({error:'path required'}); await fs.mkdir(path.dirname(p),{recursive:true}); await fs.writeFile(p,String(req.body.content??'')); send(res,{ok:true,path:path.relative(root,p)})});
app.post('/api/mkdir',async(req,res)=>{const p=safePath(root,String(req.body.path||'')); await fs.mkdir(p,{recursive:true}); send(res,{ok:true})});
app.delete('/api/file',async(req,res)=>{const p=safePath(root,String(req.body.path||'')); await fs.rm(p,{recursive:true,force:false}); send(res,{ok:true})});
app.post('/api/terminal',async(req,res)=>{const command=String(req.body.command||'').trim(); if(!command)return res.status(400).json({error:'command required'}); if(isDangerousCommand(command))return res.status(403).json({error:'Blocked by safety policy'}); const timeout=Number(req.body.timeout||process.env.COMMAND_TIMEOUT_MS||120000); const child=spawn('/bin/sh',['-lc',command],{cwd:root,env:{...process.env,HOME:process.env.HOME||root},stdio:['ignore','pipe','pipe']}); let out='',err=''; const max=Number(process.env.MAX_OUTPUT_BYTES||200000); child.stdout.on('data',b=>{out+=(b.toString()); if(out.length>max)child.kill('SIGTERM')}); child.stderr.on('data',b=>{err+=b.toString(); if(err.length>max)child.kill('SIGTERM')}); const timer=setTimeout(()=>child.kill('SIGTERM'),timeout); child.on('close',code=>{clearTimeout(timer);send(res,{code,stdout:out.slice(-max),stderr:err.slice(-max)})})});
app.get('/api/models',async(_,res)=>{const ents=await fs.readdir(modelsRoot,{withFileTypes:true}); send(res,ents.filter(e=>e.isFile()&&/\\.(gguf|bin)$/i.test(e.name)).map(e=>({name:e.name,path:path.join(modelsRoot,e.name)})))});
app.post('/api/models/download',async(req,res)=>{const url=String(req.body.url||''); const name=path.basename(new URL(url).pathname); if(!/\\.gguf$/i.test(name))return res.status(400).json({error:'Only GGUF downloads are supported'}); const dest=safePath(modelsRoot,name); const r=await fetch(url); if(!r.ok)return res.status(r.status).json({error:'download failed'}); const fh=await fs.open(dest,'w'); try{const reader=r.body.getReader(); while(true){const {done,value}=await reader.read(); if(done)break; await fh.write(value)}}finally{await fh.close()} send(res,{ok:true,name})});
app.post('/api/models/launch',async(req,res)=>{const name=String(req.body.name||''); const model=safePath(modelsRoot,name); if(!name.endsWith('.gguf'))return res.status(400).json({error:'GGUF required'}); const bin=process.env.LLAMA_BIN||'llama-server'; const port=Number(req.body.port||8080); const child=spawn(bin,['-m',model,'--host','127.0.0.1','--port',String(port),'-c',String(req.body.context||8192)],{cwd:root,detached:true,stdio:'ignore'}); child.unref(); send(res,{ok:true,pid:child.pid,baseUrl:'http://127.0.0.1:'+port+'/v1'})});
app.post('/api/agent',async(req,res)=>{const prompt=String(req.body.prompt||'').trim(); const modelUrl=String(req.body.modelUrl||'http://127.0.0.1:8080/v1/chat/completions'); if(!prompt)return res.status(400).json({error:'prompt required'}); const r=await fetch(modelUrl,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({model:req.body.model||'local',messages:[{role:'system',content:'You are a professional coding agent. Analyze the workspace, propose precise changes, and return safe executable steps. Never claim a file was changed unless the tool actually changed it.'},{role:'user',content:prompt}],temperature:Number(req.body.temperature??0.2),max_tokens:Number(req.body.maxTokens||4096)})}); const data=await r.json(); if(!r.ok)return res.status(r.status).json(data); send(res,{ok:true,text:data.choices?.[0]?.message?.content||JSON.stringify(data)})});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'..','public','index.html')));
app.use((err,_req,res,_next)=>res.status(500).json({error:err.message}));
app.listen(port,host,()=>console.log('Local Coding Agent listening on http://'+host+':'+port));
