import assert from 'node:assert/strict';
import test from 'node:test';
import {readFile} from 'node:fs/promises';
import {transform} from 'esbuild';
import {webcrypto} from 'node:crypto';
const monitor=await readFile(new URL('../worker-src/activity-monitor.ts',import.meta.url),'utf8');
const dashboard=await readFile(new URL('../worker-src/dashboard.ts',import.meta.url),'utf8');
async function compile(source,names,io={}){const js=(await transform(source.replaceAll('export ',''),{loader:'ts'})).code;return new Function(...Object.keys(io),js+';return {'+names+'};')(...Object.values(io))}
async function server(){const timers=new Set(),rows=new Map();const io={setState:async(k,v)=>{rows.set(k,v)},deleteState:async k=>{rows.delete(k)}};return {...await compile(monitor,'beginActivity,monitored,activityMiddleware,activityRequestName',{crypto:webcrypto,setInterval:fn=>{timers.add(fn);return fn},clearInterval:fn=>timers.delete(fn)}),io,rows,timers}}
function slice(from,to){return dashboard.slice(dashboard.indexOf(from),dashboard.indexOf(to,dashboard.indexOf(from)))}
async function browser(fetch){const localTasks=new Map(),timers=[];const ui=await compile(slice('function activityRequestLabel(', 'async function apiRequest(')+slice('function localTaskStart(', '/**\n * D1 daily-quota bar.'),'activityFetch,activityId,mergeActivityRuns,activityRunRow,localTaskStart,localTaskEnd',{fetch,location:{href:'http://vps.example/'},globalThis:{},activeExtractionDiagnostic:null,localTasks,activityVisible:false,setTimeout:fn=>timers.push(fn),esc:String,escAttr:String,fa:String});return {...ui,localTasks,timers}}
test('request classification is identical in browser and server and excludes polling',async()=>{const s=await server(),b=await compile(slice('function activityRequestLabel(', '// Correlation IDs'),'activityRequestLabel');for(const path of ['/api/activity','/api/status','/api/ai/test/current','/api/ai/test-results','/api/profiles','/api/settings','/api/profiles/x/benchmark-engines','/api/profiles/x/extraction-diagnostic','/api/backup','/api/ai/test','/api/import','/api/destination/woo/products','/api/branch-push','/health'])for(const method of ['GET','POST','DELETE'])assert.equal(b.activityRequestLabel(path,method),s.activityRequestName(path,method));assert.equal(s.activityRequestName('/api/activity'),null);assert.ok(s.activityRequestName('/api/ai/test','POST'));assert.ok(s.activityRequestName('/api/backup?token=secret'));});
test('concurrent durable operations have independent lifetimes and no payload secrets',async()=>{const s=await server(),a=await s.beginActivity(s.io,'backup'),b=await s.beginActivity(s.io,'AI');assert.notEqual(a.id,b.id);assert.equal(s.rows.size,2);const row=s.rows.get('activity_live:'+a.id);assert.equal(row.scope,'server');assert.equal(row.readOnly,true);assert.equal(row.progress,null);await a.finish();await a.finish();assert.equal(s.rows.size,1);await b.finish();assert.equal(s.rows.size,0);assert.equal(s.timers.size,0)});
test('heartbeat queued before completion cannot resurrect a finished activity',async()=>{const s=await server(),a=await s.beginActivity(s.io,'AI');for(const tick of s.timers)tick();await a.finish();await Promise.resolve();assert.equal(s.rows.size,0);assert.equal(s.timers.size,0)});
test('synchronous and asynchronous registry errors do not change business outcomes',async()=>{for(const fail of [()=>{throw Error('offline')},()=>Promise.reject(Error('offline'))]){const s=await server(),io={setState:fail,deleteState:fail};assert.equal(await s.monitored(io,'AI',async()=>42),42);await assert.rejects(s.monitored(io,'AI',async()=>{throw Error('business error')}),/business error/);assert.equal(s.timers.size,0)}});
test('NDJSON activity persists beyond response headers until full consumption',async()=>{const s=await server();let controller;const c={req:{path:'/api/profiles/x/extraction-diagnostic',method:'POST',header:()=>undefined},res:new Response(new ReadableStream({start(c){controller=c}}),{headers:{'content-type':'application/x-ndjson'}})};await s.activityMiddleware(s.io)(c,async()=>{});assert.equal(s.rows.size,1);const body=c.res.text();controller.enqueue(new TextEncoder().encode('{"ok":true}\n'));assert.equal(s.rows.size,1);controller.close();assert.match(await body,/ok/);assert.equal(s.rows.size,0)});
test('cancelled server stream remains unknown rather than claiming server stopped',async()=>{const s=await server(),c={req:{path:'/api/branch-push',method:'POST',header:()=>undefined},res:new Response(new ReadableStream(),{headers:{'content-type':'application/x-ndjson'}})};await s.activityMiddleware(s.io)(c,async()=>{});await c.res.body.cancel();assert.equal([...s.rows.values()][0].status,'unknown');assert.equal(s.timers.size,0)});
test('browser tracks pending bodies, concurrent requests, failures and plain HTTP IDs',async()=>{const controllers=[];const b=await browser(async(_url,options)=>{assert.match(options.headers.get('x-scraper-activity'),/^[a-f0-9-]{36}$/);return new Response(new ReadableStream({start(c){controllers.push(c)}}))});const a=await b.activityFetch('/api/import',{method:'POST'}),z=await b.activityFetch('/api/settings',{method:'POST'});assert.equal(b.localTasks.size,2);assert.ok([...b.localTasks.values()].every(r=>r.status==='running'&&r.progress===null));const read=a.json();controllers[0].enqueue(new TextEncoder().encode('{"ok":false}'));controllers[0].close();await read;assert.deepEqual([...b.localTasks.values()].map(r=>r.status),['failed','running']);await z.body.cancel();assert.equal([...b.localTasks.values()][1].status,'failed')});
test('browser network failure ends its local activity and propagates the error',async()=>{const b=await browser(async()=>{throw Error('network')});await assert.rejects(b.activityFetch('/api/import',{method:'POST'}),/network/);assert.equal([...b.localTasks.values()][0].status,'failed')});
test('polling creates no local activities; correlated remote rows are deduplicated',async()=>{const b=await browser(async()=>new Response('{}'));await b.activityFetch('/api/activity');assert.equal(b.localTasks.size,0);const local={id:'same',status:'running'},remote={id:'other',status:'running'};assert.deepEqual(b.mergeActivityRuns([local],[{id:'same',scope:'server'},remote]),[local,remote])});
test('generic read-only activities have no fake controls or percentages',async()=>{const b=await browser(async()=>new Response('{}')),html=b.activityRunRow({id:'a',kind:'operation:a',name:'backup',readOnly:true,status:'running',progress:null},true,0,1);assert.doesNotMatch(html,/data-run-delete|data-run-up|draggable|data-activity-run|width:/);assert.match(html,/سرور/)});
test('completed-task timer cannot delete a new task with the same key',async()=>{const b=await browser(async()=>new Response('{}'));b.localTaskStart('a','first');b.localTaskEnd('a',true);b.localTaskStart('a','second');b.timers[0]();assert.equal(b.localTasks.get('a').name,'second')});
test('both database implementations query all active jobs independently of recent history',async()=>{for(const file of ['render-src/db.ts','worker-src/db.ts']){const source=await readFile(new URL('../'+file,import.meta.url),'utf8'),fn=source.slice(source.indexOf('export async function listActiveJobs('),source.indexOf('export async function listLiveActivities('));assert.match(fn,/status IN \('queued','running'\)/);assert.doesNotMatch(fn,/LIMIT|SELECT \*/);assert.match(source,/substr\(key,1,14\)='activity_live:'/)}const node=await readFile(new URL('../render-src/server.ts',import.meta.url),'utf8');assert.match(node,/getCurrentAiRun\(\),getPublicCategoryRun\(\),getPublicDedupRun\(\),listLiveActivities\(\)/)});
test('Node activity response includes 35 old active jobs and all supported non-job runs',async()=>{const source=await readFile(new URL('../render-src/server.ts',import.meta.url),'utf8'),a=source.indexOf("app.get('/api/activity',"),b=source.indexOf('\n});',a)+4;let handler;const jobs=Array.from({length:35},(_,i)=>({id:'job-'+i,status:'queued',createdAt:String(i).padStart(2,'0'),total:0,processed:0}));await compile(source.slice(a,b),'',{...await compile(await readFile(new URL('../worker-src/job-details.ts',import.meta.url),'utf8'),'extractionDetails'),app:{get:(_path,fn)=>{handler=fn}},listProfiles:async()=>[],listJobs:async()=>[{id:'recent',status:'done'}],listActiveJobs:async()=>jobs,getCurrentAiRun:async()=>({id:'ai',status:'running',total:2,cursor:1}),getPublicCategoryRun:async()=>({id:'category',status:'queued'}),getPublicDedupRun:async()=>({id:'dedup',status:'paused'}),listLiveActivities:async()=>[{id:'operation',status:'running',readOnly:true}],getJobPriorities:async()=>({'job-34':100}),getRunPriorities:async()=>({}),runtimeVersion:()=> 'test'});const data=await handler({req:{query:()=>undefined},json:v=>v});assert.equal(data.activeJobs.length,35);assert.equal(data.activeJobs[0].id,'job-34');assert.equal(data.runs.length,4);assert.equal(data.counts.runningRuns,3);assert.equal(data.runs.find(r=>r.id==='ai').progress,50);assert.equal(data.lastJobs[0].id,'recent')});
test('both registries mark stale heartbeats unknown and tolerate pruning failure',async()=>{for(const file of ['render-src/db.ts','worker-src/db.ts']){const source=await readFile(new URL('../'+file,import.meta.url),'utf8'),rows=[{value:JSON.stringify({id:'fresh',status:'running',updatedAt:new Date().toISOString()})},{value:JSON.stringify({id:'stale',status:'running',updatedAt:new Date(Date.now()-100000).toISOString()})}];const {listLiveActivities}=await compile(source.slice(source.indexOf('export async function listLiveActivities(')),'listLiveActivities',{useSqlite:true,sqliteCutoff:()=> 'sqlite cutoff',parseJson:JSON.parse,json:JSON.parse,pool:{query:async(sql,args)=>{if(sql.startsWith('DELETE')){assert.equal(args[0],'sqlite cutoff');throw Error('prune failed')}return {rows}}},run:async()=>{throw Error('prune failed')},rows:async()=>rows});const result=await listLiveActivities();assert.deepEqual(result.map(r=>r.status),['running','unknown'])}});
test('finish waits for an already in-flight heartbeat before deleting',async()=>{const s=await server(),a=await s.beginActivity(s.io,'AI');let release;s.io.setState=(key,value)=>new Promise(resolve=>{release=()=>{s.rows.set(key,value);resolve()}});for(const tick of s.timers)tick();await Promise.resolve();assert.ok(release);const finished=a.finish();assert.equal(s.rows.size,1);release();await finished;assert.equal(s.rows.size,0)});
