import assert from 'node:assert/strict';
import test from 'node:test';
import {readFile} from 'node:fs/promises';
import {transform} from 'esbuild';
const read=p=>readFile(new URL('../'+p,import.meta.url),'utf8');
async function compile(source,names,io={}){const js=(await transform(source.replace(/^import .*;\s*$/gm,'').replaceAll('export ',''),{loader:'ts'})).code;return new Function(...Object.keys(io),js+';return {'+names+'};')(...Object.values(io))}
const core=await compile(await read('worker-src/destination-ledger.ts'),'createDestinationLedger,desiredProduct,digest,ledgerScope,LEDGER_TTL,equivalentDesired');
const list=await compile(await read('worker-src/source-list-ledger.ts'),'reuseSourceList,sourceDetailFailed',core);
const adjustments=await compile(await read('worker-src/result-adjustments.ts'),'applyResultAdjustments');
function store(){const state=new Map(),rows=new Map();let fail=false;const io={getState:async(k,f)=>structuredClone(state.get(k)??f),setState:async(k,v)=>{state.set(k,structuredClone(v))},ledgerGet:async(s,g,id)=>structuredClone(rows.get([s,g,id].join('|'))??null),ledgerRows:async(s,g)=>[...rows].filter(([k])=>k.startsWith(s+'|'+g+'|')).map(([,v])=>structuredClone(v)),ledgerPut:async(s,g,entries)=>{if(fail)throw Error('disk full');for(const e of entries)rows.set([s,g,String(e.remote.id)].join('|'),structuredClone(e))},ledgerPrune:async()=>{}};return {io,state,rows,fail:value=>{fail=value},ledger:core.createDestinationLedger(io)}}
const remote=(id='1',price=100)=>({id,name:'Shoe',sku:'sku-1',price,status:'publish',raw:{price:String(price),description:'Description',short_description:'Short',stock_quantity:5,images:[{src:'https://shop.test/image.jpg'}],categories:[{id:7}]}});
const product=()=>({sourceKey:'s1',title:'Shoe',sku:'sku-1',price:100,priceText:'100 تومان',stock:5,longDesc:'Description',shortDesc:'Short',images:['https://shop.test/image.jpg']});
const profile={id:'p1',selectors:{container:'.product'},gallery:{},titleSuffix:'',priceMode:'percent',priceValue:20,roundPrice:0,wooCategoryId:7};
test('complete snapshots persist across instances and fresh scans are reused',async()=>{const s=store();let calls=0;const fetch=async()=>{calls++;return [remote()]};await s.ledger.refresh('woo',fetch);const restarted=core.createDestinationLedger(s.io);assert.equal((await restarted.refresh('woo',fetch)).cached,true);assert.equal(calls,1);assert.equal((await restarted.entries('woo'))[0].remote.price,100)});
test('failed fetch, duplicate pages, and partial writes never replace the previous snapshot',async()=>{const s=store();await s.ledger.refresh('woo',async()=>[remote()]);const before=await s.ledger.metadata('woo');await assert.rejects(s.ledger.refresh('woo',async()=>{throw Error('page 2 timeout')},true));await assert.rejects(s.ledger.refresh('woo',async()=>[remote(),remote()],true),/تکراری/);s.fail(true);await assert.rejects(s.ledger.refresh('woo',async()=>[remote('2')],true),/disk full/);assert.deepEqual(await s.ledger.metadata('woo'),before);assert.equal((await s.ledger.entries('woo'))[0].remote.id,'1')});
test('concurrent callers share one in-flight scan',async()=>{const s=store();let resolve,calls=0,signal;const started=new Promise(r=>{signal=r});const fetch=()=>{calls++;signal();return new Promise(r=>{resolve=r})};const a=s.ledger.refresh('woo',fetch),b=s.ledger.refresh('woo',fetch);await started;resolve([remote()]);await Promise.all([a,b]);assert.equal(calls,1)});
test('account scope isolates stores, stalls, and endpoints without persisting secrets',async()=>{const a=await core.ledgerScope('woo','https://user:password@one.test/shop/?token=secret','default'),b=await core.ledgerScope('woo','https://two.test/shop/','default'),c=await core.ledgerScope('basalam','https://api.test/v1','1'),d=await core.ledgerScope('basalam','https://api.test/v1','2');assert.notEqual(a,b);assert.notEqual(c,d);assert.doesNotMatch(a,/password|secret|one.test/)});
test('snapshot strips unrelated remote metadata and fingerprints exclude credentials',async()=>{const s=store();await s.ledger.refresh('woo',async()=>[{...remote(),raw:{...remote().raw,meta_data:[{key:'token',value:'secret'}],password:'hidden'}}]);assert.doesNotMatch(JSON.stringify(await s.ledger.entries('woo')),/secret|hidden/);assert.doesNotMatch(JSON.stringify(core.desiredProduct(product(),profile,{target:'woo',apiKey:'secret',token:'hidden'})),/secret|hidden/)});
test('verified fields can skip the very first write; changed specifications cannot',()=>{const desired=core.desiredProduct(product(),profile,{target:'woo',pricePercent:0,contentSync:true});assert.equal(core.equivalentDesired(remote(),desired),true);for(const patch of [{price:120},{name:'Other'},{raw:{...remote().raw,stock_quantity:2}},{raw:{...remote().raw,description:'Edited'}},{raw:{...remote().raw,images:[]}}])assert.equal(core.equivalentDesired({...remote(),...patch},desired),false)});
test('receipts skip only identical, fresh desired state and unknown writes invalidate them',async()=>{const s=store(),desired=core.desiredProduct(product(),profile,{target:'woo'});await s.ledger.confirm('woo',remote(),desired,'p1','s1');let entry=await s.ledger.find('woo','1');assert.equal(await s.ledger.matches(entry,desired),true);assert.equal(await s.ledger.matches(entry,{...desired,product:{...desired.product,price:120}}),false);await s.ledger.invalidate('woo','1');assert.equal(await s.ledger.matches(await s.ledger.find('woo','1'),desired),false);assert.equal((await s.ledger.find('woo','1')).profileId,'p1');assert.equal(await s.ledger.matches({...entry,at:new Date(Date.now()-core.LEDGER_TTL-1).toISOString()},desired),false)});
test('external edits observed by a newer scan invalidate a previous receipt',async()=>{const s=store(),desired=core.desiredProduct(product(),profile,{target:'woo'});await s.ledger.confirm('woo',remote(),desired,'p1','s1','2020-01-01T00:00:00.000Z');await s.ledger.refresh('woo',async()=>[remote('1',130)]);const entry=await s.ledger.find('woo','1');assert.equal(entry.remote.price,130);assert.equal(await s.ledger.matches(entry,desired),false);assert.equal(entry.profileId,'p1')});
test('successful update/delete overlays change the ledger without scanning again',async()=>{const s=store();await s.ledger.refresh('woo',async()=>[remote()]);await s.ledger.patch('woo','1',{price:150});assert.equal((await s.ledger.entries('woo'))[0].remote.price,150);await s.ledger.patch('woo','1',{},true);assert.equal((await s.ledger.entries('woo')).length,0)});
test('huge marketplace IDs remain exact and ambiguous SKUs are never guessed',async()=>{const s=store(),id='3838404244461599744';await s.ledger.refresh('woo',async()=>[remote(id),remote('2')]);assert.equal((await s.ledger.find('woo',id)).remote.id,id);assert.equal(await s.ledger.find('woo',null,'sku-1'),null)});
test('a broken published snapshot fails rather than presenting an empty destination',async()=>{const s=store();await s.ledger.refresh('woo',async()=>[remote()]);s.rows.clear();await assert.rejects(s.ledger.entries('woo'),/ناقص/)});
test('unchanged initial list reuses details, while list/config changes and audit expiry re-read them',async()=>{const fresh={...product(),longDesc:'',shortDesc:''},first=await list.reuseSourceList(structuredClone(fresh),null,profile);first.longDesc='Detailed description';adjustments.applyResultAdjustments(first,profile);const next=await list.reuseSourceList(structuredClone(fresh),first,profile);assert.equal(next._reuseDetails,true);assert.equal(next.longDesc,'Detailed description');assert.equal(next.price,100);assert.equal((await list.reuseSourceList({...fresh,price:101},first,profile))._reuseDetails,undefined);assert.equal((await list.reuseSourceList(structuredClone(fresh),first,{...profile,selectors:{container:'.new'}}))._reuseDetails,undefined);first.sourceList.checkedAt='2020-01-01';assert.equal((await list.reuseSourceList(structuredClone(fresh),first,profile))._reuseDetails,undefined)});
test('reusing source detail/variant prices does not compound profile adjustments',async()=>{const fresh={...product(),variationPrices:{large:200},variationGroups:[{name:'Size',values:['large'],prices:{large:200}}]};const first=await list.reuseSourceList(structuredClone(fresh),null,profile);adjustments.applyResultAdjustments(first,profile);assert.equal(first.variationPrices.large,240);const next=await list.reuseSourceList(structuredClone(fresh),first,profile);delete next.resultBase;adjustments.applyResultAdjustments(next,{...profile,priceValue:30});assert.equal(next.price,130);assert.equal(next.variationPrices.large,260);assert.equal(next.variationGroups[0].prices.large,260)});
test('failed detail fetches are not cached as a successfully checked source list',async()=>{const fresh=product(),first=await list.reuseSourceList(structuredClone(fresh),null,profile);adjustments.applyResultAdjustments(first,profile);list.sourceDetailFailed(first);assert.equal((await list.reuseSourceList(structuredClone(fresh),first,profile))._reuseDetails,undefined)});
for(const runtime of ['worker','render'])test(runtime+': actual Woo send skips identical repeat and sends changed final price',async()=>{const s=store(),source=await read(runtime+'-src/sync.ts'),a=source.indexOf('export async function syncWoo('),b=source.indexOf('\n}',a)+2;let writes=0,pricePercent=0;const network=async(url,options)=>{if(!options.method)return new Response('[]');writes++;const payload=JSON.parse(options.body);return new Response(JSON.stringify({id:1,name:payload.name,sku:payload.sku,price:payload.regular_price,status:'publish',description:payload.description,short_description:payload.short_description,images:payload.images,categories:payload.categories,stock_quantity:payload.stock_quantity}))};const {syncWoo}=await compile(source.slice(a,b),'syncWoo',{destinationLedger:s.ledger,destinationScope:async()=> 'woo',desiredProduct:core.desiredProduct,loadConnections:async()=>({woo:{url:'https://woo.test',key:'key',secret:'secret',pricePercent}}),getRemoteId:async()=>1,setRemoteId:async()=>{},setDestinationId:async()=>{},getState:async()=>({}),safeFetch:network,safeWooFetch:network,toRemoteId:x=>x,basicAuth:()=> 'auth',Buffer});assert.equal(await syncWoo(product(),profile),'created');assert.equal(await syncWoo(product(),profile),'unchanged');assert.equal(writes,1);pricePercent=10;assert.equal(await syncWoo(product(),profile),'updated');assert.equal(writes,2);assert.equal((await s.ledger.find('woo','1')).remote.price,110)});
for(const runtime of ['worker','render'])test(runtime+': retirement requires current complete source scan, positive ownership, fresh ledger and explicit policy',async()=>{const source=await read(runtime+'-src/maintenance.ts'),a=source.indexOf('export async function ledgerMissing('),b=source.indexOf('\n}',a)+2;let complete=false,active=false,owner='other',changed=0,mode='delete';const rows=[{profile_id:'p1',source_key:'s1',title:'Shoe',active:false,maps:[{target:'woo',account_key:'default',remote_id:'1'}]}],entry={remote:remote(),profileId:'p1',sourceKey:'s1'};const {ledgerMissing}=await compile(source.slice(a,b),'ledgerMissing',{maintenanceRows:async()=>rows.map(r=>({...r,active})),getState:async k=>k==='settings'?{retire:{mode}}:{complete,jobId:'j'},reconAccounts:async()=>[{target:'woo',accountKey:'default',name:'Woo'}],destinationScope:async()=> 'woo',destinationLedger:{metadata:async()=>({startedAt:new Date().toISOString()}),find:async()=>({...entry,profileId:owner})},destinationProduct:async()=>remote(),destinationDelete:async(_t,_id,force)=>{assert.equal(force,false);changed++},wooUpdate:async()=>{changed++}});await ledgerMissing('p1',true);assert.equal(changed,0);complete=true;await ledgerMissing('p1',true);assert.equal(changed,0);owner='p1';active=true;await ledgerMissing('p1',true);assert.equal(changed,0);active=false;mode='report';await ledgerMissing('p1',true);assert.equal(changed,0);mode='delete';assert.equal((await ledgerMissing('p1',true)).changed,1);assert.equal(changed,1)});
