import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {transform} from 'esbuild';
const read=p=>readFile(new URL('../'+p,import.meta.url),'utf8');
async function compile(source,names,io={}){const js=(await transform(source.replaceAll('export ',''),{loader:'ts'})).code;return new Function(...Object.keys(io),js+';return {'+names+'};')(...Object.values(io))}
const server=await read('worker-src/maintenance-response.ts'),dashboard=await read('worker-src/dashboard.ts');
test('live maintenance sends headers and heartbeat before slow work completes',async()=>{const timers=new Set();const {maintenanceResponse}=await compile(server,'maintenanceResponse',{setInterval:fn=>{timers.add(fn);return fn},clearInterval:fn=>timers.delete(fn)});let resolve;const response=await maintenanceResponse({req:{query:()=> '1'},executionCtx:{waitUntil:()=>{}}},()=>new Promise(r=>{resolve=r}));assert.match(response.headers.get('content-type'),/ndjson/);assert.equal(response.headers.get('x-accel-buffering'),'no');const reader=response.body.getReader(),decode=new TextDecoder();assert.match(decode.decode((await reader.read()).value),/started/);for(const tick of timers)tick();assert.match(decode.decode((await reader.read()).value),/heartbeat/);resolve({ok:true,planned:3});assert.match(decode.decode((await reader.read()).value),/planned/);assert.equal((await reader.read()).done,true);assert.equal(timers.size,0)});
test('maintenance exceptions are structured and legacy callers retain JSON',async()=>{const {maintenanceResponse}=await compile(server,'maintenanceResponse');const c={req:{query:()=> '1'}};const response=await maintenanceResponse(c,async()=>{throw Error('destination timeout')});assert.match(await response.text(),/"type":"error".*destination timeout/);assert.deepEqual(await maintenanceResponse({req:{query:()=>undefined},json:x=>x},async()=>({ok:true})),{ok:true})});
test('disconnect clears heartbeat without claiming the server work was cancelled',async()=>{const timers=new Set();const {maintenanceResponse}=await compile(server,'maintenanceResponse',{setInterval:fn=>{timers.add(fn);return fn},clearInterval:fn=>timers.delete(fn)});let finish,done=false;const response=await maintenanceResponse({req:{query:()=> '1'}},async()=>{await new Promise(r=>{finish=r});done=true;return {ok:true}});await response.body.cancel();assert.equal(timers.size,0);assert.equal(done,false);finish();await Promise.resolve();await Promise.resolve();assert.equal(done,true)});
async function browser(fetch){const button={disabled:false},source=dashboard.slice(dashboard.indexOf('let maintenanceBusy='),dashboard.indexOf('async function apiRequest(')),results=[];const ui=await compile(source,'maintenanceRequest',{document:{querySelectorAll:()=>[button]},activityFetch:fetch,U:x=>x,headers:()=>({'content-type':'application/json'}),activityResponseResult:(_r,data)=>results.push(data)});return {...ui,button,results}}
test('client decodes chunked UTF-8 events, ignores heartbeats and restores controls',async()=>{const bytes=new TextEncoder().encode('{"type":"started"}\n{"type":"heartbeat"}\n{"type":"result","data":{"ok":false,"error":"خطا"}}\n');const ui=await browser(async url=>{assert.match(url,/\?live=1$/);return new Response(new ReadableStream({start(c){for(const byte of bytes)c.enqueue(Uint8Array.of(byte));c.close()}}),{headers:{'content-type':'application/x-ndjson'}})});const result=await ui.maintenanceRequest('/api/maintenance/duplicates',{method:'POST'});assert.equal(result.error,'خطا');assert.equal(result.ok,false);assert.equal(ui.button.disabled,false);assert.equal(ui.results.length,1)});
test('missing final result is an error, not a successful empty report',async()=>{const ui=await browser(async()=>new Response('{"type":"heartbeat"}\n',{headers:{'content-type':'application/x-ndjson'}}));await assert.rejects(ui.maintenanceRequest('/api/maintenance/recon-unified',{}),/تأیید نشده/);assert.equal(ui.button.disabled,false)});
test('network errors are actionable and destructive operations are never retried',async()=>{let calls=0;const ui=await browser(async()=>{calls++;throw TypeError('Failed to fetch')});await assert.rejects(ui.maintenanceRequest('/api/maintenance/duplicates',{method:'POST'}),/دوباره اجرا نکنید/);assert.equal(calls,1);assert.equal(ui.button.disabled,false)});
test('concurrent maintenance requests are blocked and older JSON servers still work',async()=>{let finish,calls=0;const ui=await browser(()=>{calls++;return new Promise(r=>{finish=r})});const running=ui.maintenanceRequest('/api/maintenance/duplicates',{});assert.equal(ui.button.disabled,true);await assert.rejects(ui.maintenanceRequest('/api/maintenance/duplicates',{}),/صبر کنید/);finish(new Response('{"ok":true}'));assert.equal((await running).ok,true);assert.equal(calls,1);assert.equal(ui.button.disabled,false)});
test('reconciliation menu has one preview, separate duplicate actions, and collapsed repair tools',()=>{const menu=dashboard.slice(dashboard.indexOf(" ['🔍 مغایرت‌گیری با مقصد'"),dashboard.indexOf(" ['🧠 یادگیری دسته‌بندی'"));assert.match(menu,/'recon-unified-preview'/);assert.match(menu,/'dupes-preview'/);assert.match(menu,/<details><summary>/);assert.doesNotMatch(menu,/'recon-woo'|'recon-basalam'|'recontable-woo'|'recontable-basalam'|'recon-unified'|'stats'/);assert.match(dashboard,/lastReconReport=d;const html=renderReconMatrix/)});
