import assert from 'node:assert/strict';
import test from 'node:test';
import {readFile} from 'node:fs/promises';
import {transform} from 'esbuild';
import {load} from 'cheerio';
const read=f=>readFile(new URL('../'+f,import.meta.url),'utf8');
async function compile(source,names,io={}){const js=(await transform(source.replaceAll('export ',''),{loader:'ts'})).code;return new Function(...Object.keys(io),js+';return {'+names+'};')(...Object.values(io))}
const {collectScrollProducts}=await compile(await read('worker-src/scroll-collector.ts'),'collectScrollProducts');
const fixture=load(await read('worker-tests/fixtures/scroll-delayed.html'));
const batches=fixture('template').toArray().map(el=>({at:Number(fixture(el).attr('data-at')),products:load(fixture(el).html())('.product').toArray().map(card=>({key:fixture(card).find('a').attr('href'),price:Number(fixture(card).find('.price').text())}))}));
test('lab reproduction: a snapshot sees one batch, not the four delayed/virtualized batches',()=>{assert.equal(batches[0].products.length,1);assert.equal(new Set(batches.flatMap(b=>b.products.map(p=>p.key))).size,4)});
test('scroll collector keeps removed DOM cards, waits for slow pending fetch and collects all four batches',async()=>{let now=0;const result=await collectScrollProducts({snapshot:async()=>batches.filter(b=>b.at<=now).at(-1).products,step:async()=>({height:1000,top:500,atEnd:true,pending:now>=2500&&now<17500}),key:p=>p.key,now:()=>now,wait:async ms=>{now+=ms}});assert.equal(result.length,4);assert.deepEqual(result.map(p=>p.price),[1000,2000,3000,4000]);assert.ok(now>=27500)});
test('height stability alone is not completion and a timeout fails instead of returning a partial list',async()=>{let now=0;await assert.rejects(collectScrollProducts({snapshot:async()=>[{key:String(now)}],step:async()=>({height:1000,top:500,atEnd:true}),key:p=>p.key,now:()=>now,wait:async ms=>{now+=ms}},{timeoutMs:2000}),/تأیید نشد/)});
test('scrolling must reach bottom, supports cancellation and propagates snapshot failures',async()=>{for(const mode of ['not-bottom','stop','network']){let now=0;await assert.rejects(collectScrollProducts({snapshot:async()=>{if(mode==='network')throw Error('network failed');return []},step:async()=>({height:10000,top:10,atEnd:false}),key:p=>p.key,now:()=>now,wait:async ms=>{now+=ms},stopped:async()=>mode==='stop'},{timeoutMs:1000}))}});
test('product and round caps are explicit failures, not successful truncation',async()=>{const io={snapshot:async()=>[{key:'one'}],step:async()=>({height:1,top:1,atEnd:true}),key:p=>p.key,now:()=>0,wait:async()=>{}};await assert.rejects(collectScrollProducts(io,{maxProducts:1}),/سقف/);await assert.rejects(collectScrollProducts(io,{maxRounds:2}),/تأیید نشد/)});
async function repriceIO(){const helper=await compile(await read('worker-src/woo-reprice.ts'),'saveConnectionsAndReprice,drainWooReprice'),states=new Map(),jobs=[],dispatched=[];let current={woo:{url:'https://woo.example',key:'key',secret:'secret',pricePercent:0}},fail=false;const io={loadConnections:async()=>structuredClone(current),mergeConnections:(before,input)=>({...before,woo:{...before.woo,...input.woo}}),saveConnections:async input=>(current={...current,woo:{...current.woo,...input.woo}}),listProfiles:async()=>[{id:'a',enabled:true,syncWoo:false},{id:'b',enabled:true,syncWoo:true},{id:'disabled',enabled:false}],getState:async(k,f)=>structuredClone(states.get(k)??f),setState:async(k,v)=>{states.set(k,structuredClone(v))},createJob:async(id,kind,target,options)=>{if(fail&&id==='b')throw Error('queue unavailable');const job={id,kind,target,options};jobs.push(job);return job},dispatch:async job=>{dispatched.push(job)}};return {...helper,io,states,jobs,dispatched,fail:value=>{fail=value}}}
test('Woo percentage change queues only Woo for every active profile, including destination-disabled profiles',async()=>{const h=await repriceIO(),result=await h.saveConnectionsAndReprice({woo:{pricePercent:20}},h.io);assert.equal(result.connections.woo.pricePercent,20);assert.deepEqual(h.jobs.map(j=>j.id),['a','b']);assert.ok(h.jobs.every(j=>j.target==='woo'&&j.kind==='sync'&&j.options.priceSync));assert.equal(h.dispatched.length,2);assert.deepEqual(h.states.get('woo_price_sync_pending').ids,[])});
test('unchanged saves and unrelated connection edits do not resend products',async()=>{const h=await repriceIO();await h.saveConnectionsAndReprice({woo:{pricePercent:0}},h.io);await h.saveConnectionsAndReprice({woo:{key:'new-key'}},h.io);assert.equal(h.jobs.length,0)});
test('failed queue fan-out survives a settings save and resumes without repeating completed profiles',async()=>{const h=await repriceIO();h.fail(true);await assert.rejects(h.saveConnectionsAndReprice({woo:{pricePercent:-10}},h.io),/queue unavailable/);assert.equal((await h.io.loadConnections()).woo.pricePercent,-10);assert.deepEqual(h.states.get('woo_price_sync_pending').ids,['b']);h.fail(false);await h.drainWooReprice(h.io);assert.deepEqual(h.jobs.map(j=>j.id),['a','b'])});
test('latest change supersedes a partially dispatched price request; zero is a real change',async()=>{const h=await repriceIO();h.fail(true);await assert.rejects(h.saveConnectionsAndReprice({woo:{pricePercent:20}},h.io));h.fail(false);await h.saveConnectionsAndReprice({woo:{pricePercent:0}},h.io);assert.deepEqual(h.jobs.map(j=>j.id),['a','a','b']);assert.equal(h.states.get('woo_price_sync_pending').percent,0)});
const dashboard=await read('worker-src/dashboard.ts');
test('product price table starts with source price and applied profile adjustment for every destination',async()=>{const a=dashboard.indexOf('function openProductModal('),b=dashboard.indexOf('\n',a);let html;const {openProductModal}=await compile(dashboard.slice(a,b),'openProductModal',{state:{selected:'p',profiles:[{id:'p',priceMode:'percent',priceValue:99}],productRows:[{sourceKey:'x',price:120,resultBase:{price:100,priceText:'100 تومان'},resultApplied:{priceMode:'percent',priceValue:20},images:[]}]},productCodeSuffix:()=>'',allDestinationsForPricing:()=>[{name:'Woo',percent:10},{name:'Basalam',percent:5,toRial:true}],destinationPrice:(price,percent,rial)=>Math.round(price*(1+percent/100))*(rial?10:1),fa:String,esc:String,escAttr:String,headlineFinalPrice:()=>132,safeProductHtml:String,modalShell:(_title,value)=>{html=value}});openProductModal('x');const $=load(html),rows=$('.pdest-table').first().find('tbody tr');assert.equal(rows.length,2);assert.equal(rows.eq(0).find('td').eq(0).text(),'100 تومان');assert.equal(rows.eq(0).find('td').eq(1).text(),'20٪');assert.equal(rows.eq(1).find('td').eq(0).text(),'100 تومان');assert.match(rows.eq(0).text(),/132 تومان/)});
for(const runtime of ['worker','render'])test(runtime+': product report captures original price separately from destination price',async()=>{const source=await read(runtime+'-src/processor.ts'),a=source.indexOf('function reportItem('),b=runtime==='worker'?source.indexOf('\n',a):source.indexOf('\n}',a)+2;const {reportItem}=await compile(source.slice(a,b),'reportItem');const row=reportItem({sourceKey:'x',price:120,resultBase:{price:100,priceText:'100 تومان'}},{target:'basalam',price:1260});assert.equal(row.basePrice,100);assert.equal(row.price,1260);assert.equal(row.basePriceText,'100 تومان');assert.equal(reportItem({price:120}).basePrice,undefined)});
for(const runtime of ['worker','render'])test(runtime+': Woo updates existing ID or SKU with fresh destination percentage',async()=>{const source=await read(runtime+'-src/sync.ts'),a=source.indexOf('export async function syncWoo('),b=source.indexOf('\n}',a)+2;for(const mapped of [42,null]){const requests=[];const transport=async(url,options)=>{requests.push({url,options});return new Response(JSON.stringify(options.method?{id:42}:[{id:42}]),{status:200})};const {syncWoo}=await compile(source.slice(a,b),'syncWoo',{loadConnections:async fresh=>{assert.equal(fresh,true);return{woo:{url:'https://woo.example',key:'a',secret:'b',pricePercent:20}}},getRemoteId:async()=>mapped,getState:async()=>({}),setRemoteId:async()=>{},setDestinationId:async()=>{},safeFetch:transport,safeWooFetch:transport,basicAuth:()=> 'auth',toRemoteId:x=>x,Buffer});assert.equal(await syncWoo({sourceKey:'x',price:100,images:[],title:'A'}, {id:'p'}),'updated');const call=requests.at(-1);assert.match(call.url,/\/products\/42$/);assert.equal(JSON.parse(call.options.body).regular_price,'120')}});
test('scroll mode has twin URL semantics and Worker refuses to fake browser completeness',async()=>{for(const runtime of ['worker','render']){const source=await read(runtime+'-src/scraper.ts');assert.match(source,/profile\.pagination\s*===\s*'scroll'/)}const source=await read('worker-src/scraper.ts'),a=source.indexOf('export async function scrapeListPage('),b=source.indexOf('\nexport async function scrapeList(',a);const {scrapeListPage}=await compile(source.slice(a,b),'scrapeListPage');await assert.rejects(scrapeListPage('https://shop.example',{},'',false,'auto',undefined,true,true,true),/Node/)});
test('Node scroll runs use guarded browser networking and never retire on inferred scroll completion',async()=>{const scraper=await read('render-src/scraper.ts'),processor=await read('render-src/processor.ts'),browser=await read('render-src/visual-browser.ts');assert.match(scraper,/renderBrowserSnapshot\(url,driver,indirect/);assert.match(browser,/session\?\.prepare\(page\)/);assert.match(browser,/await session.collect\(page\)/);assert.match(processor,/profile.pagination==='scroll'.*\?0:await markMissingProducts/);assert.match(processor,/profile.pagination === 'none' \|\| profile.pagination === 'scroll'\) break/)});
test('real Node scroll adapter targets the inner list, accumulates virtualized snapshots and cleans request listeners',async()=>{
 const source=await read('render-src/scraper.ts'),a=source.indexOf('function trackScrollRequests('),b=source.indexOf('async function scrapeRenderedHtml(',a);let time=0,top=0,started=false,finished=false;
 const root={scrollHeight:1000,clientHeight:500,parentElement:null,get scrollTop(){return top},set scrollTop(n){top=Math.min(500,n)}},documentRoot={scrollTop:0},listeners=new Map(),request={resourceType:()=> 'fetch'},emit=(name,arg)=>{for(const fn of listeners.get(name)||[])fn(arg)};
 const page={on:(name,fn)=>{if(!listeners.has(name))listeners.set(name,new Set());listeners.get(name).add(fn)},off:(name,fn)=>listeners.get(name).delete(fn),url:()=> 'https://shop.example/',evaluate:async(fn,selector)=>fn(selector),content:async()=>{if(time>=2500&&!started){started=true;emit('request',request)}if(time>=17500&&!finished){finished=true;emit('requestfinished',request)}return String(batches.filter(x=>x.at<=time).length-1)}};
 const {collectRenderedScroll}=await compile(source.slice(a,b),'collectRenderedScroll',{collectScrollProducts,parseProductsFromHtml:html=>batches[Number(html)].products.map(p=>({...p,sourceKey:p.key})),rescueRenderedProducts:(_html,_url,products)=>({products}),xpathToCss:()=>null,document:{scrollingElement:documentRoot,querySelector:()=>({parentElement:root}),querySelectorAll:()=>[]},getComputedStyle:()=>({overflowY:'auto'}),Date:{now:()=>time},setTimeout:(fn,ms)=>{time+=ms;fn()}});
 const result=await collectRenderedScroll(page,{container:'.product'});assert.equal(result.length,4);assert.equal(documentRoot.scrollTop,0);assert.equal(root.scrollTop,500);assert.ok([...listeners.values()].every(set=>set.size===0));
});
