import { aiCall, aiProviders } from './ai.js';
import { loadConnections } from './connections.js';
import { addAutoreplyLog, getState, listAutoreplyLog, maintenanceRows, setState } from './db.js';
import { safeFetch } from './network.js';
import { sendNotification } from './notifications.js';

type Rule={id?:string;on?:boolean;match?:'contains'|'exact'|'starts'|'regex'|'always';triggers?:string;reply?:string;priority?:number;daily_max?:number};
const norm=(v:string)=>String(v||'').toLowerCase().replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/[\u200c\u200f\u200e]/g,' ').replace(/\s+/g,' ').trim();
const DEFAULT_RULES:Rule[]=[{id:'hello',on:true,match:'contains',triggers:'سلام|درود|وقت بخیر',reply:'سلام و وقت بخیر 🌹 در خدمتم.',priority:10,daily_max:100},{id:'thanks',on:true,match:'contains',triggers:'ممنون|متشکر|سپاس',reply:'خواهش می‌کنم 🌷',priority:20,daily_max:100},{id:'bye',on:true,match:'contains',triggers:'خداحافظ|خدانگهدار',reply:'خدانگهدار 🌹 هر زمان سؤالی داشتید در خدمتم.',priority:30,daily_max:100}];
export function matchRule(rules:Rule[],text:string):Rule|null{const sorted=rules.filter(r=>r.on!==false&&r.reply).sort((a,b)=>(a.priority||50)-(b.priority||50));for(const rule of sorted)if(ruleMatch(rule,text))return rule;return null}
function ruleMatch(rule:Rule,text:string){if(rule.match==='always')return true;const value=norm(text);for(const raw of String(rule.triggers||'').split(/[\r\n|]+/)){const trigger=norm(raw);if(!trigger)continue;if(rule.match==='exact'&&value===trigger)return true;if(rule.match==='starts'&&value.startsWith(trigger))return true;if((!rule.match||rule.match==='contains')&&value.includes(trigger))return true;if(rule.match==='regex')try{if(new RegExp(raw,'iu').test(text))return true}catch{}}return false}
export async function generateReply(text:string){const settings=await getState<any>('settings',{}),cfg=settings.autoreply||{},rules=Array.isArray(cfg.rules)&&cfg.rules.length?cfg.rules:DEFAULT_RULES,order=cfg.order||cfg.reply_order||'rules_first',rule=matchRule(rules,text);const fromRule=()=>rule?{text:String(rule.reply),source:`rule:${rule.id||'rule'}`} : null,fromAi=async()=>{try{const providers=await aiProviders(),p=providers.find(x=>x.enabled&&x.models.length);if(!p)return null;const response=await aiCall(p,p.models[0],`تو پشتیبان مؤدب فروشگاه هستی. کوتاه و فارسی پاسخ بده. پیام مشتری: ${text}`);return{text:response.text,source:`ai:${p.id}::${p.models[0]}`}}catch{return null}};if(order==='rules_only')return fromRule();if(order==='ai_only')return fromAi();if(order==='ai_first')return await fromAi()||fromRule();return fromRule()||await fromAi()}
export async function autoreplyRun(dry=true){const settings=await getState<any>('settings',{}),cfg=settings.autoreply||{};if(!dry&&!cfg.enabled)throw Error('پاسخ خودکار فعال نیست');const chats=await basalamChats(Number(cfg.scanLimit)||20),state=await getState<any>('autoreply_state',{chats:{},day:'',daily:{}}),items:any[]=[];let replied=0,skipped=0,failed=0;for(const chat of chats.slice(0,Math.min(50,Number(cfg.maxPerRun)||5))){const chatId=Number(chat.id||chat.chat_id),messages=await chatMessages(chatId,20),last=messages.find((m:any)=>isCustomer(m));if(!last){skipped++;continue}const msgId=String(last.id||last.message_id||''),text=messageText(last),now=Date.now(),lastAt=messageTime(last),previous=state.chats?.[chatId];if(!text||previous?.msgId===msgId){skipped++;continue}if(Number(cfg.graceMin||10)>0&&lastAt&&now-lastAt<Number(cfg.graceMin||10)*60000){skipped++;items.push({chatId,text,skip:'مهلت انتظار پیام'});continue}if(previous?.at&&now-Number(previous.at)<Number(cfg.perChatMin||180)*60000){skipped++;items.push({chatId,text,skip:'فاصله پاسخ به گفتگو'});continue}if(cfg.onlyOffhours&&!offHours(Number(cfg.workFrom??9),Number(cfg.workTo??21))){skipped++;continue}const answer=await generateReply(text);if(!answer){items.push({chatId,text,skip:'بدون پاسخ'});skipped++;continue}const row:any={chatId,customer:chat.customer?.name||chat.user?.name||chat.title||'',input:text,reply:answer.text,source:answer.source,status:dry?'ارسال می‌شد':'در انتظار'};if(dry){replied++;items.push(row);continue}try{await sendChat(chatId,answer.text+(cfg.sign?`\n${cfg.sign}`:''));state.chats??={};state.chats[chatId]={msgId,at:Date.now(),source:answer.source};await addAutoreplyLog({chatId,customer:row.customer,input:text,output:answer.text,source:answer.source});row.status='ارسال شد';replied++}catch(error){row.status=error instanceof Error?error.message:String(error);failed++}items.push(row)}if(!dry)await setState('autoreply_state',state);return{ok:failed===0,dry,checked:chats.length,replied,skipped,failed,items}}
export async function basalamChats(limit=20){const c=(await loadConnections()).basalam;if(!c.token)throw Error('توکن باسلام خالی است');const r=await safeFetch(`${c.api}/chats?limit=${Math.min(50,limit)}&order_by=updated_at`,{headers:{authorization:`Bearer ${c.token}`,accept:'application/json'}},3_000_000),body=await r.json() as any;if(!r.ok)throw Error(`Basalam chats HTTP ${r.status}`);return body?.data?.chats||body?.data||[]}
export async function basalamOrders(perPage=20){const c=(await loadConnections()).basalam;if(!c.token||!c.vendorId)throw Error('اتصال باسلام کامل نیست');const r=await safeFetch(`${c.api}/vendor-parcels?items.vendor_ids=${encodeURIComponent(c.vendorId)}&per_page=${Math.min(30,perPage)}`,{headers:{authorization:`Bearer ${c.token}`,accept:'application/json'}},5_000_000),body=await r.json() as any;if(!r.ok)throw Error(`Basalam orders HTTP ${r.status}`);return body?.data||[]}
async function chatMessages(chatId:number,limit=20){const c=(await loadConnections()).basalam,r=await safeFetch(`${c.api}/chats/${chatId}/messages?limit=${limit}&order=desc`,{headers:{authorization:`Bearer ${c.token}`,accept:'application/json'}},3_000_000),body=await r.json() as any;if(!r.ok)throw Error(`Chat messages HTTP ${r.status}`);return body?.data?.messages||body?.data||[]}
async function sendChat(chatId:number,text:string){const c=(await loadConnections()).basalam,r=await safeFetch(`${c.api}/chats/${chatId}/messages`,{method:'POST',headers:{authorization:`Bearer ${c.token}`,'content-type':'application/json'},body:JSON.stringify({content:{text:text.slice(0,3000)},message_type:'text'})},2_000_000);if(!r.ok)throw Error(`Send chat HTTP ${r.status}`)}
function isCustomer(m:any){const role=String(m.sender_type||m.sender?.type||m.role||'').toLowerCase();return !['vendor','seller','shop','admin'].includes(role)}
function messageText(m:any){return String(m.content?.text||m.text||m.message||'').trim()}
function messageTime(m:any){const value=m.created_at||m.createdAt||m.date||m.timestamp;if(!value)return 0;const n=Number(value);return Number.isFinite(n)&&n>1e9?(n<1e12?n*1000:n):Date.parse(value)||0}
function offHours(from:number,to:number){const hour=new Date().getHours();if(from===to)return false;return from<to?!(hour>=from&&hour<to):!(hour>=from||hour<to)}
export async function digest(preview=true){const rows=await maintenanceRows(''),previous=await getState<Record<string,any>>('digest_snapshot',{}),current:Record<string,any>={};for(const row of rows)current[`${row.profile_id}:${row.source_key}`]={title:row.title,price:Number(row.price),active:row.active};const added=[],removed=[],changed=[];for(const [key,value] of Object.entries(current)){if(!previous[key])added.push(value);else if(previous[key].price!==value.price)changed.push({...value,oldPrice:previous[key].price})}for(const [key,value] of Object.entries(previous))if(!current[key]||!current[key].active)removed.push(value);const text=`🌙 گزارش محصولات\n➕ جدید: ${added.length}\n💰 تغییر قیمت: ${changed.length}\n🗑 حذف/ناموجود: ${removed.length}`;const delivery:any[]=[];if(!preview){await setState('digest_snapshot',current);const n=(await loadConnections()).notifications;for(const [channel,on] of [['bale',n.baleToken&&n.baleChatId],['rubika',n.rubikaToken&&n.rubikaChatId],['webhook',n.url]] as const)if(on)try{delivery.push({channel,...await sendNotification(channel as any,text)})}catch(error){delivery.push({channel,error:error instanceof Error?error.message:String(error)})}}return{ok:true,preview,text,added:added.slice(0,100),removed:removed.slice(0,100),changed:changed.slice(0,100),counts:{added:added.length,removed:removed.length,changed:changed.length},delivery}}
export async function autoreplyLogs(){return listAutoreplyLog(100)}
export async function automationTick(){const settings=await getState<any>('settings',{}),result:any={};if(settings.autoreply?.enabled)try{result.autoreply=await autoreplyRun(false)}catch(error){result.autoreply={error:error instanceof Error?error.message:String(error)}}const d=settings.digest||{},timezone=String(d.timezone||'Asia/Tehran'),parts=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'}).formatToParts(new Date()),part=(name:string)=>parts.find(x=>x.type===name)?.value||'',today=`${part('year')}-${part('month')}-${part('day')}`,hour=Number(part('hour')),state=await getState<any>('digest_run',{});if(d.enabled&&hour===Number(d.hour??23)&&state.day!==today)try{result.digest=await digest(false);await setState('digest_run',{day:today,at:new Date().toISOString()})}catch(error){result.digest={error:error instanceof Error?error.message:String(error)}}return result}
