import { pool } from './db.js';
import { loadConnections, connectionStatus } from './connections.js';

export type Capability={id:string;section:string;label:string;status:'operational'|'adapted'|'account-dependent';endpoint?:string;note?:string};

// Inventory mirrors the actionable controls in scraper4.php v9.80's hamburger menu.
export const PHP_MENU_CAPABILITIES:Capability[]=[
 {id:'settings-export',section:'backup',label:'دانلود همه تنظیمات و پروفایل‌ها',status:'operational',endpoint:'/api/settings-export'},
 {id:'settings-import',section:'backup',label:'بارگذاری و بازیابی تنظیمات',status:'operational',endpoint:'/api/settings-import'},
 {id:'changelog',section:'version',label:'تغییرات نسخه‌ها',status:'adapted',note:'Git history / RENDER-PARITY.md'},
 {id:'version-check',section:'version',label:'بررسی نسخه کد',status:'adapted',note:'Render deploy status'},
 {id:'version-update',section:'version',label:'نصب نسخه جدید',status:'adapted',note:'Render auto deploy/rollback'},
 {id:'backup-full',section:'backup',label:'بکاپ کامل داده',status:'operational',endpoint:'/api/backup'},
 {id:'backup-restore',section:'backup',label:'بازیابی بکاپ Render',status:'operational',endpoint:'/api/restore'},
 {id:'woo-save',section:'woo',label:'ذخیره اتصال ووکامرس',status:'operational',endpoint:'/api/connections'},
 {id:'woo-test',section:'woo',label:'تست ووکامرس',status:'operational',endpoint:'/api/test-connection/woo'},
 {id:'woo-category',section:'woo',label:'دسته پیش‌فرض ووکامرس',status:'operational'},
 {id:'basalam-save',section:'basalam',label:'ذخیره اتصال باسلام',status:'operational',endpoint:'/api/connections'},
 {id:'basalam-test',section:'basalam',label:'تست باسلام',status:'operational',endpoint:'/api/test-connection/basalam'},
 {id:'basalam-multishop',section:'basalam',label:'مدیریت چند غرفه',status:'operational'},
 {id:'basalam-indirect',section:'basalam',label:'اتصال غیرمستقیم',status:'account-dependent',note:'برای AI کامل؛ API باسلام بسته به Proxy'},
 {id:'ai-import',section:'ai',label:'درون‌ریزی ارائه‌دهندگان AI',status:'operational',endpoint:'/api/connections'},
 {id:'ai-providers',section:'ai',label:'ارائه‌دهندگان AI',status:'operational',endpoint:'/api/ai/providers'},
 {id:'ai-test-all',section:'ai',label:'تست همه مدل‌ها',status:'operational',endpoint:'/api/ai/test-all'},
 {id:'ai-models',section:'ai',label:'فهرست مدل‌ها',status:'operational',endpoint:'/api/ai/providers'},
 {id:'ai-candidates',section:'ai',label:'مدل‌های کاندید',status:'operational'},
 {id:'ai-master',section:'ai',label:'مدل مستر',status:'operational'},
 {id:'ai-vote',section:'ai',label:'رأی مدل',status:'operational',endpoint:'/api/ai/vote'},
 {id:'ai-leaderboard',section:'ai',label:'جدول امتیازات',status:'operational',endpoint:'/api/ai/leaderboard'},
 {id:'ai-network',section:'ai',label:'روش اتصال AI',status:'operational'},
 {id:'ai-probe',section:'ai',label:'عیب‌یابی AI',status:'operational',endpoint:'/api/ai/test-all'},
 {id:'notify-save',section:'notifications',label:'ذخیره اعلان‌ها',status:'operational',endpoint:'/api/connections'},
 {id:'notify-bale',section:'notifications',label:'تست بله',status:'operational',endpoint:'/api/notifications/test'},
 {id:'notify-rubika',section:'notifications',label:'تست روبیکا',status:'operational',endpoint:'/api/notifications/test'},
 {id:'notify-webhook',section:'notifications',label:'تست Webhook',status:'operational',endpoint:'/api/notifications/test'},
 {id:'orders',section:'notifications',label:'استعلام سفارش‌ها',status:'operational',endpoint:'/api/basalam/orders'},
 {id:'chats',section:'notifications',label:'استعلام گفتگوها',status:'operational',endpoint:'/api/basalam/chats'},
 {id:'retire-preview',section:'retire',label:'پیش‌نمایش محصولات رفته',status:'operational',endpoint:'/api/maintenance/retire/woo'},
 {id:'retire-apply',section:'retire',label:'اعمال وضعیت محصولات رفته',status:'operational',endpoint:'/api/maintenance/retire/woo'},
 {id:'general-save',section:'general',label:'ذخیره تنظیمات عمومی',status:'operational',endpoint:'/api/settings'},
 {id:'queue-status',section:'general',label:'وضعیت صف‌ها',status:'operational',endpoint:'/api/jobs'},
 {id:'security-check',section:'general',label:'بررسی امنیت',status:'operational',endpoint:'/api/selftest'},
 {id:'watchdog',section:'watchdog',label:'نگهبان صف',status:'operational',endpoint:'/api/queue-watchdog'},
 {id:'selftest',section:'watchdog',label:'خودآزمون نصب',status:'operational',endpoint:'/api/selftest'},
 {id:'source-test',section:'source',label:'آزمایش اتصال مبدأ',status:'operational',endpoint:'/api/source-test'},
 {id:'source-network',section:'source',label:'تنظیم مسیر شبکه مبدأ',status:'account-dependent',note:'Fetch امن مستقیم؛ proxy برای AI'},
 {id:'recon-woo',section:'recon',label:'مغایرت‌گیری ووکامرس',status:'operational',endpoint:'/api/maintenance/recon/woo'},
 {id:'recon-basalam',section:'recon',label:'مغایرت‌گیری باسلام',status:'operational',endpoint:'/api/maintenance/recon/basalam'},
 {id:'map-status',section:'recon',label:'وضعیت Remote Map',status:'operational',endpoint:'/api/profile-stats'},
 {id:'map-rebuild-woo',section:'recon',label:'بازسازی نگاشت ووکامرس',status:'operational',endpoint:'/api/maintenance/rebuild/woo'},
 {id:'map-rebuild-basalam',section:'recon',label:'بازسازی نگاشت باسلام',status:'operational',endpoint:'/api/maintenance/rebuild/basalam'},
 {id:'category-list',section:'category',label:'نمایش آموخته‌ها',status:'operational',endpoint:'/api/category-learning'},
 {id:'category-test',section:'category',label:'آزمایش دسته عنوان',status:'operational',endpoint:'/api/category-learning/test'},
 {id:'category-record',section:'category',label:'ثبت یادگیری دسته',status:'operational',endpoint:'/api/category-learning/record'},
 {id:'bulk-woo',section:'editor',label:'ویرایش گروهی ووکامرس',status:'operational',endpoint:'/api/maintenance/bulk/woo'},
 {id:'bulk-basalam',section:'editor',label:'ویرایش گروهی باسلام',status:'operational',endpoint:'/api/maintenance/bulk/basalam'},
 {id:'photo-preview',section:'photo',label:'پیش‌نمایش محصولات بدون عکس',status:'operational',endpoint:'/api/maintenance/photo-fix'},
 {id:'photo-apply',section:'photo',label:'عکس‌دارکردن ووکامرس',status:'operational',endpoint:'/api/maintenance/photo-fix'},
 {id:'autoreply-test',section:'autoreply',label:'آزمایش پاسخ خودکار',status:'operational',endpoint:'/api/autoreply/test'},
 {id:'autoreply-preview',section:'autoreply',label:'پیش‌نمایش گفتگوها',status:'operational',endpoint:'/api/autoreply/run'},
 {id:'autoreply-run',section:'autoreply',label:'اجرای پاسخ خودکار',status:'operational',endpoint:'/api/autoreply/run'},
 {id:'autoreply-log',section:'autoreply',label:'گزارش پاسخ‌ها',status:'operational',endpoint:'/api/autoreply/log'},
 {id:'digest-preview',section:'digest',label:'پیش‌نمایش گزارش شبانه',status:'operational',endpoint:'/api/digest'},
 {id:'digest-send',section:'digest',label:'ارسال گزارش شبانه',status:'operational',endpoint:'/api/digest'}
];

export async function runSelftest(){const checks:Array<{name:string;ok:boolean;detail?:string}>=[];const check=async(name:string,fn:()=>Promise<string|void>)=>{try{const detail=await fn();checks.push({name,ok:true,detail:detail||undefined})}catch(error){checks.push({name,ok:false,detail:error instanceof Error?error.message:String(error)})}};await check('database',async()=>{await pool.query('SELECT 1');return'PostgreSQL connected'});await check('schema',async()=>{const required=['profiles','products','jobs','app_state','destination_map','category_learning','autoreply_log'],{rows}=await pool.query(`SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_name=ANY($1::text[])`,[required]),found=rows.map(x=>x.table_name),missing=required.filter(x=>!found.includes(x));if(missing.length)throw Error('Missing: '+missing.join(','));return`${found.length} tables`});await check('menu-inventory',async()=>{if(PHP_MENU_CAPABILITIES.length!==57)throw Error(`Expected 57, got ${PHP_MENU_CAPABILITIES.length}`);const ids=PHP_MENU_CAPABILITIES.map(x=>x.id);if(new Set(ids).size!==ids.length)throw Error('Duplicate capability ID');return'57 unique operations'});await check('vault',async()=>{const value=await loadConnections(true);return JSON.stringify(connectionStatus(value))});await check('destructive-guards',async()=>"Retire, bulk edit and photo fix require APPLY");const operational=PHP_MENU_CAPABILITIES.filter(x=>x.status==='operational').length,adapted=PHP_MENU_CAPABILITIES.filter(x=>x.status==='adapted').length,dependent=PHP_MENU_CAPABILITIES.filter(x=>x.status==='account-dependent').length;return{ok:checks.every(x=>x.ok),checks,summary:{total:57,operational,adapted,accountDependent:dependent},capabilities:PHP_MENU_CAPABILITIES,at:new Date().toISOString()}}
