#!/data/data/com.termux/files/usr/bin/bash
# Scraper 4 — installer for Termux (Android).
#
# One command, from a fresh Termux:
#   pkg install -y curl && \
#   curl -fsSL https://raw.githubusercontent.com/fazilatma/new/arena/01a0bd3f-new/python-scraper4/tools/install_termux.sh | bash
#
# Afterwards (all defined inside THIS file, see write_launcher below):
#   scraper4 start     # run it
#   scraper4 stop
#   scraper4 restart
#   scraper4 status
#   scraper4 log
#   scraper4 update    # pull the newest version AND refresh the scraper4
#                      # command itself (it re-runs this installer)
#
# Modes (used by `scraper4 update` for self-refresh):
#   (no args)      full install
#   --update       same as full install, but fast: skips pkg/pip when present
#   --update-local app files + launcher only; caller already did the git pull
#   --launcher     regenerate ${PREFIX}/bin/scraper4 and exit
#
# Opens on http://127.0.0.1:8000/ui in the phone's browser.
#
# Notes for Android:
#  * No root, no systemd. The app runs as a normal background process and is
#    kept alive by Termux itself, so acquire a wakelock for long extractions.
#  * Playwright/Selenium need a desktop Chromium and are NOT installed here;
#    the HTTP engines (requests, httpx, curl_cffi, cloudscraper) are what work
#    on a phone, and the app already falls back to them.
#  * lxml and curl_cffi need compilers; we install the Termux packages that
#    provide prebuilt wheels where possible and continue if one fails.
set -u

REPO_URL="${REPO_URL:-https://github.com/fazilatma/new.git}"
BRANCH="${BRANCH:-arena/01a0bd3f-new}"
SUBDIR="python-scraper4"

MODE="install"
case "${1:-}" in
  --update)       MODE="update" ;;
  --update-local) MODE="update-local" ;;
  --launcher)     MODE="launcher" ;;
esac

HOME_DIR="${HOME:-/data/data/com.termux/files/home}"
SRC="${HOME_DIR}/scraper4-src"
RUN="${HOME_DIR}/scraper4"
VENV="${RUN}/venv"
PY="${VENV}/bin/python"
BIN="${PREFIX:-/data/data/com.termux/files/usr}/bin"

say()  { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m    %s\033[0m\n' "$*" >&2; }
die()  { printf '\n\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

case "$(uname -o 2>/dev/null || true)" in
  *Android*) ;;
  *) [ -d /data/data/com.termux/files/usr ] || \
       die "This script is for Termux on Android." ;;
esac

# ── the scraper4 command ────────────────────────────────────────────────────
# Single source of truth: start|stop|restart|status|log|update all live here,
# so `scraper4 update` (which re-runs this file) refreshes the commands too.
write_launcher() {
  mkdir -p "$BIN"
  cat > "${BIN}/scraper4" <<TERMUXEOF
#!/data/data/com.termux/files/usr/bin/bash
# Scraper 4 launcher (Termux) — generated by tools/install_termux.sh.
# Do not edit here: edit the installer in the repo and run \`scraper4 update\`.
set -u
RUN="${RUN}"
PY="${PY}"
SRC="${SRC}"
PORT="\${SCRAPER_PORT:-8000}"
# Local-only by default. SCRAPER_BIND=0.0.0.0 exposes it to the LAN.
BIND="\${SCRAPER_BIND:-127.0.0.1}"

export PYTHONUNBUFFERED=1
export SCRAPER_RUNTIME=termux
# No reverse proxy on a phone: serve straight from the root so /ui works at
# http://127.0.0.1:8000/ui (the /put prefix is only for the Apache setup).
export SCRAPER_URL_PREFIX=""
export SCRAPER_AUTO_UPDATE=0
export SCRAPER_GIT_AUTO_UPDATE=0
export SCRAPER_REPO_DIR="\$SRC"
export SCRAPER_DATA_FILE="\${RUN}/scraper4_data.json"
export SCRAPER_LIVE_DIR="\${RUN}/scraper4-live"
export SCRAPER_ERROR_LOG="\${RUN}/scraper4-errors.jsonl"

running() { pgrep -f "gunicorn.*scraper4:application" >/dev/null 2>&1; }

do_stop() {
  pkill -f "gunicorn.*scraper4:application" 2>/dev/null || true
  command -v termux-wake-unlock >/dev/null 2>&1 && termux-wake-unlock || true
}

do_start() {
  running && { echo "Already running: http://127.0.0.1:\${PORT}/ui"; return 0; }
  # One worker: task state lives in this process. timeout 0: never kill a
  # long extraction.
  cd "\$RUN" || return 1
  nohup "\$PY" -m gunicorn --bind "\${BIND}:\${PORT}" --workers 1 --threads 4 \\
    --timeout 0 --graceful-timeout 30 scraper4:application \\
    >"\${RUN}/scraper4.log" 2>&1 &
  sleep 3
  if running; then
    command -v termux-wake-lock >/dev/null 2>&1 && termux-wake-lock || true
    echo "Started -> http://127.0.0.1:\${PORT}/ui"
  else
    echo "Failed to start. Last lines:"; tail -n 20 "\${RUN}/scraper4.log"; return 1
  fi
}

do_update() {
  echo "Fetching update for ${BRANCH}..."
  FETCH_OK=0
  if git -C "\$SRC" fetch --depth 1 origin "${BRANCH}" >/dev/null 2>&1; then
    if git -C "\$SRC" reset --hard FETCH_HEAD >/dev/null 2>&1; then
      FETCH_OK=1
    elif git -C "\$SRC" reset --hard "origin/${BRANCH}" >/dev/null 2>&1; then
      FETCH_OK=1
    fi
  fi
  if [ "\$FETCH_OK" -eq 0 ]; then
    echo "Shallow fetch failed, trying full fetch..."
    if git -C "\$SRC" fetch origin "${BRANCH}" >/dev/null 2>&1; then
      git -C "\$SRC" reset --hard FETCH_HEAD >/dev/null 2>&1 || git -C "\$SRC" reset --hard "origin/${BRANCH}" >/dev/null 2>&1 || {
        echo "Reset failed, trying fresh clone..."
        CLONE_URL=\$(git -C "\$SRC" remote get-url origin 2>/dev/null || echo "https://github.com/fazilatma/new.git")
        rm -rf "\${SRC}.tmp"
        if git clone --depth 1 --branch "${BRANCH}" "\$CLONE_URL" "\${SRC}.tmp" >/dev/null 2>&1; then
          rm -rf "\$SRC"; mv "\${SRC}.tmp" "\$SRC"
        else
          echo "Update failed (reset and clone)"; return 1
        fi
      }
    else
      echo "Fetch failed, trying fresh clone..."
      CLONE_URL=\$(git -C "\$SRC" remote get-url origin 2>/dev/null || echo "https://github.com/fazilatma/new.git")
      rm -rf "\${SRC}.tmp"
      if git clone --depth 1 --branch "${BRANCH}" "\$CLONE_URL" "\${SRC}.tmp" >/dev/null 2>&1; then
        rm -rf "\$SRC"; mv "\${SRC}.tmp" "\$SRC"
      else
        echo "Update failed (fetch and clone)"; return 1
      fi
    fi
  fi
  INSTALLER=""
  for cand in "\${SRC}/${SUBDIR}/tools/install_termux.sh" "\${SRC}/tools/install_termux.sh"; do
    [ -f "\$cand" ] && INSTALLER="\$cand" && break
  done
  if [ -n "\$INSTALLER" ]; then
    # Re-run the freshly pulled installer: it copies the app files AND
    # regenerates this very command, so start|stop|status|log|update stay
    # in sync with the repo automatically.
    bash "\$INSTALLER" --update-local || return 1
  else
    # Fallback for old checkouts without the installer: inline file refresh.
    APP="\${SRC}/${SUBDIR}"; [ -f "\${APP}/scraper4.py" ] || APP="\$SRC"
    cp -a "\${APP}/"*.py "\$RUN/"
    [ -f "\${APP}/ui_bridge.py" ] && cp -a "\${APP}/ui_bridge.py" "\$RUN/"
    [ -d "\${APP}/ui" ] && { rm -rf "\${RUN}/ui"; cp -a "\${APP}/ui" "\${RUN}/ui"; }
    find "\$RUN" -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
  fi
  echo "Updated. Run: scraper4 restart  (or stop && start) to apply"
}

case "\${1:-help}" in
  start)   do_start ;;
  stop)    do_stop; echo "Stopped." ;;
  restart) do_stop; sleep 1; do_start ;;
  status)
    if running; then
      echo "Running -> http://127.0.0.1:\${PORT}/ui"
      curl -s "http://127.0.0.1:\${PORT}/health" 2>/dev/null | head -c 300; echo
    else
      echo "Not running."
    fi
    ;;
  log)     tail -n "\${2:-40}" "\${RUN}/scraper4.log" ;;
  update)  do_update ;;
  help|*)  echo "usage: scraper4 {start|stop|restart|status|log|update}" ;;
esac
TERMUXEOF
  chmod +x "${BIN}/scraper4"
}

if [ "$MODE" = "launcher" ]; then
  write_launcher
  say "Regenerated scraper4 command: ${BIN}/scraper4"
  exit 0
fi

if [ "$MODE" != "update-local" ]; then
  say "1/6 Installing base packages"
  # python-lxml and libxml2 save a long compile; without them pip builds from
  # source and usually fails on a phone.
  pkg update -y >/dev/null 2>&1 || warn "pkg update failed; continuing"
  pkg install -y python git libxml2 libxslt libjpeg-turbo zlib clang \
    binutils openssl libffi python-lxml >/dev/null 2>&1 \
    || pkg install -y python git >/dev/null 2>&1 \
    || die "Failed to install base packages"
  command -v python3 >/dev/null 2>&1 || die "python3 not installed"
  command -v git >/dev/null 2>&1 || die "git not installed"

  say "2/6 Fetching code from ${BRANCH}"
  # Diagnostic before fetch — helps debug "stuck on 10.176"
  SRC_COMMIT_BEFORE="$(git -C "$SRC" rev-parse --short HEAD 2>/dev/null || echo "none")"
  SRC_VER_BEFORE="$(grep -m1 '^APP_VERSION' "$SRC/python-scraper4/scraper4.py" 2>/dev/null | cut -d'"' -f2)"
  [ -z "$SRC_VER_BEFORE" ] && SRC_VER_BEFORE="$(grep -m1 '^APP_VERSION' "$SRC/scraper4.py" 2>/dev/null | cut -d'"' -f2)"
  RUN_VER_BEFORE="$(grep -m1 '^APP_VERSION' "$RUN/scraper4.py" 2>/dev/null | cut -d'"' -f2)"
  echo "  Before: SRC $SRC_COMMIT_BEFORE ver ${SRC_VER_BEFORE:-?} RUN ver ${RUN_VER_BEFORE:-?}"
  if [ -d "${SRC}/.git" ]; then
    git -C "$SRC" remote set-url origin "$REPO_URL" 2>/dev/null || true
    FETCH_OK=0
    if git -C "$SRC" fetch --depth 1 origin "$BRANCH" >/dev/null 2>&1; then
      if git -C "$SRC" reset --hard FETCH_HEAD >/dev/null 2>&1; then
        FETCH_OK=1
      elif git -C "$SRC" reset --hard "origin/$BRANCH" >/dev/null 2>&1; then
        FETCH_OK=1
      fi
    fi
    if [ "$FETCH_OK" -eq 0 ]; then
      if git -C "$SRC" fetch origin "$BRANCH" >/dev/null 2>&1; then
        git -C "$SRC" reset --hard FETCH_HEAD >/dev/null 2>&1 || git -C "$SRC" reset --hard "origin/$BRANCH" >/dev/null 2>&1 || {
          warn "Fetch succeeded but reset failed; trying fresh clone"
          rm -rf "${SRC}.tmp"
          if git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "${SRC}.tmp" >/dev/null 2>&1; then
            rm -rf "$SRC"; mv "${SRC}.tmp" "$SRC"
          else
            warn "Fresh clone also failed; using existing checkout"
          fi
        }
      else
        warn "Fetch failed; trying fresh clone"
        rm -rf "${SRC}.tmp"
        if git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "${SRC}.tmp" >/dev/null 2>&1; then
          rm -rf "$SRC"; mv "${SRC}.tmp" "$SRC"
        else
          warn "Fresh clone also failed; using existing checkout"
        fi
      fi
    fi
  else
    rm -rf "${SRC}.tmp"
    git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "${SRC}.tmp" \
      || die "git clone failed (check internet connection)"
    rm -rf "$SRC"; mv "${SRC}.tmp" "$SRC"
  fi
  # Post-fetch diagnostics — force fresh clone if still stuck on old version
  SRC_VER_AFTER="$(grep -m1 '^APP_VERSION' "$SRC/python-scraper4/scraper4.py" 2>/dev/null | cut -d'"' -f2)"
  [ -z "$SRC_VER_AFTER" ] && SRC_VER_AFTER="$(grep -m1 '^APP_VERSION' "$SRC/scraper4.py" 2>/dev/null | cut -d'"' -f2)"
  SRC_COMMIT_AFTER="$(git -C "$SRC" rev-parse --short HEAD 2>/dev/null || echo "?")"
  SRC_BRANCH_AFTER="$(git -C "$SRC" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "?")"
  echo "  After fetch: SRC $SRC_COMMIT_AFTER ($SRC_BRANCH_AFTER) ver ${SRC_VER_AFTER:-?}"
  if [ "$SRC_VER_AFTER" = "10.176" ] || [ "$SRC_VER_AFTER" = "10.179" ] || [ "$SRC_VER_AFTER" = "10.180" ] || [ "$SRC_VER_AFTER" = "10.181" ]; then
    # If still not on the newest expected (will be 10.182 after bump), try one more fresh clone
    # We check for older versions specifically so we don't loop when already fresh
    if [ "$SRC_VER_AFTER" != "" ]; then
      warn "SRC still on old $SRC_VER_AFTER, forcing fresh clone to get latest"
      rm -rf "${SRC}.tmp" "${SRC}.bak"
      mv "$SRC" "${SRC}.bak" 2>/dev/null || true
      if git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "${SRC}.tmp" 2>&1 | head -n 20; then
        if grep -q '^APP_VERSION' "${SRC}.tmp/python-scraper4/scraper4.py" 2>/dev/null; then
          rm -rf "$SRC"; mv "${SRC}.tmp" "$SRC"; rm -rf "${SRC}.bak"
          SRC_VER_AFTER="$(grep -m1 '^APP_VERSION' "$SRC/python-scraper4/scraper4.py" 2>/dev/null | cut -d'"' -f2)"
          echo "  Fresh clone fixed: SRC ver $SRC_VER_AFTER commit $(git -C "$SRC" rev-parse --short HEAD 2>/dev/null)"
        else
          warn "Fresh clone missing scraper4.py; restoring backup"
          rm -rf "${SRC}.tmp"; mv "${SRC}.bak" "$SRC" 2>/dev/null || true
        fi
      else
        warn "Fresh clone failed; restoring backup"
        rm -rf "${SRC}.tmp"; mv "${SRC}.bak" "$SRC" 2>/dev/null || true
      fi
    fi
  fi
fi
APP="${SRC}/${SUBDIR}"
[ -f "${APP}/scraper4.py" ] || APP="$SRC"
[ -f "${APP}/scraper4.py" ] || die "scraper4.py not found in repository"

say "3/6 Creating Python environment"
mkdir -p "$RUN"
[ -x "$PY" ] || python3 -m venv --system-site-packages "$VENV" \
  || die "Failed to create venv"

if [ "$MODE" = "install" ] || ! "$PY" -c "import flask,gunicorn,requests,bs4" >/dev/null 2>&1; then
  say "4/6 Installing Python dependencies"
  "$PY" -m pip install --quiet --upgrade pip >/dev/null 2>&1 || true
  "$PY" -m pip install --quiet flask gunicorn requests beautifulsoup4 \
    || die "Failed to install core dependencies"
  # lxml usually comes from the Termux package via --system-site-packages.
  "$PY" -c "import lxml" 2>/dev/null || "$PY" -m pip install --quiet lxml \
    || warn "lxml not installed; app will use built-in parser"
  # Optional engines, one by one so a single failure does not stop the rest.
  for spec in "httpx[http2]" cloudscraper curl_cffi selectolax basalam-sdk; do
    name="${spec%%[*}"
    if "$PY" -m pip install --quiet "$spec" >/dev/null 2>&1; then
      printf '    installed: %s\n' "$name"
    else
      warn "not installed (optional): $name"
    fi
  done
else
  say "4/6 Dependencies already satisfied (skipping)"
fi

say "5/6 Installing app files"
cp -a "${APP}/"*.py "$RUN/"
if [ -f "${APP}/ui_bridge.py" ] && [ -d "${APP}/ui" ]; then
  cp -a "${APP}/ui_bridge.py" "$RUN/"
  rm -rf "${RUN}/ui"; cp -a "${APP}/ui" "${RUN}/ui"
else
  warn "Dashboard files not found; /ui will be unavailable"
fi
[ -f "${APP}/ai_providers.json" ] && [ ! -f "${RUN}/ai_providers.json" ] \
  && cp -a "${APP}/ai_providers.json" "$RUN/" || true
find "$RUN" -name '*.pyc' -delete 2>/dev/null || true
find "$RUN" -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
# Verify that RUN actually got the new version; retry once if mismatch
SRC_VER="$(grep -m1 '^APP_VERSION' "${APP}/scraper4.py" 2>/dev/null | cut -d'"' -f2)"
RUN_VER="$(grep -m1 '^APP_VERSION' "${RUN}/scraper4.py" 2>/dev/null | cut -d'"' -f2)"
echo "  Copy check: SRC $SRC_VER -> RUN $RUN_VER"
if [ -n "$SRC_VER" ] && [ "$SRC_VER" != "$RUN_VER" ]; then
  warn "Version mismatch after copy (src=$SRC_VER run=$RUN_VER); retrying"
  cp -a "${APP}/"*.py "$RUN/"
  [ -f "${APP}/ui_bridge.py" ] && cp -a "${APP}/ui_bridge.py" "$RUN/"
  [ -d "${APP}/ui" ] && { rm -rf "${RUN}/ui"; cp -a "${APP}/ui" "${RUN}/ui"; }
  sync 2>/dev/null || true
  RUN_VER="$(grep -m1 '^APP_VERSION' "${RUN}/scraper4.py" 2>/dev/null | cut -d'"' -f2)"
  echo "  After retry: RUN $RUN_VER"
fi
if [ "$SRC_VER" = "10.176" ] || [ -z "$SRC_VER" ]; then
  warn "SRC appears stuck on $SRC_VER — git may be cached; try: rm -rf $SRC && curl ... | bash"
fi
"$PY" -m py_compile "${RUN}/scraper4.py" || die "scraper4.py is invalid"

say "6/6 Creating scraper4 command"
write_launcher

VER="$(grep -m1 '^APP_VERSION' "${RUN}/scraper4.py" | cut -d'"' -f2)"
if [ "$MODE" = "update-local" ] || [ "$MODE" = "update" ]; then
  say "Update complete — version ${VER:-?}"
else
  say "Install complete — version ${VER:-?}"
fi
cat <<INFO

  Run      :  scraper4 start
  Stop     :  scraper4 stop
  Restart  :  scraper4 restart
  Status   :  scraper4 status
  Log      :  scraper4 log
  Update   :  scraper4 update   (also refreshes the scraper4 command itself)

  Dashboard:  http://127.0.0.1:8000/ui

  Notes:
   • For long extractions, keep Termux in the foreground or
     run termux-wake-lock (the script does this automatically on start).
   • Browser engines (Playwright/Selenium) are not installed on phones;
     HTTP engines work and the app falls back to them automatically.
   • Data file: ${RUN}/scraper4_data.json

INFO

# Auto-restart if an instance is already running so the new version
# is actually served. Without this, files are updated but the old
# gunicorn process keeps serving the previous APP_VERSION.
if pgrep -f "gunicorn.*scraper4:application" >/dev/null 2>&1; then
  say "Restarting running instance to apply version ${VER:-?}..."
  "${BIN}/scraper4" restart || warn "Auto-restart failed; run: scraper4 restart"
  sleep 2
  HEALTH_VER="$(curl -s http://127.0.0.1:8000/health 2>/dev/null | grep -o '"version"[[:space:]]*:[[:space:]]*"[^"]*"' | cut -d'"' -f4)"
  if [ -n "$HEALTH_VER" ] && [ "$HEALTH_VER" != "$VER" ]; then
    warn "Health still reports $HEALTH_VER != file $VER — killing stale gunicorn"
    pkill -9 -f "gunicorn.*scraper4:application" 2>/dev/null || true
    sleep 1
    "${BIN}/scraper4" start || true
    HEALTH_VER="$(curl -s http://127.0.0.1:8000/health 2>/dev/null | grep -o '"version"[[:space:]]*:[[:space:]]*"[^"]*"' | cut -d'"' -f4)"
    echo "  Health after second restart: $HEALTH_VER"
  fi
else
  # Not running — verify file version matches SRC
  echo "  Not running, file version $VER (SRC $SRC_VER)"
fi
# Final diagnostic hint for stuck 10.176
if [ "$VER" = "10.176" ]; then
  warn "Still on 10.176 — run manually: rm -rf $SRC && curl -fsSL \"https://raw.githubusercontent.com/fazilatma/new/$BRANCH/python-scraper4/tools/install_termux.sh?\$(date +%s)\" | bash"
fi
